var XLS={};
(function(F){function R(a){return String.fromCharCode(a)}function Na(a){return"undefined"!==typeof Buffer?new Buffer(a,"binary"):a.split("").map(function(a){return a.charCodeAt(0)&255})}function Oa(a){return"undefined"!==typeof Buffer?Buffer.concat(a):[].concat.apply([],a)}function I(a,b){var c,e,d,f;b=b||"u";"ieee754"===a&&(a=8,b="f");switch(a){case 1:c=this.readUInt8(this.l);break;case 2:c="u"===b?this.readUInt16LE(this.l):this.readInt16LE(this.l);break;case 4:c=this.readUInt32LE(this.l);break;
case 8:if("f"===b){c=this.readDoubleLE(this.l);break}case 16:c=this.toString("hex",this.l,this.l+a);break;case "utf8":a=b;c=this.utf8(this.l,this.l+a);break;case "utf16le":a=2*b;c=this.utf16le(this.l,this.l+a);break;case "lpstr":c=this.lpstr(this.l);a=5+c.length;break;case "lpwstr":c=this.lpwstr(this.l);a=5+c.length;"\x00"==c[c.length-1]&&(a+=2);break;case "dbcs":a=2*b;c="";f=this.l;for(d=0;d!=b;++d){if(this.lens&&-1!==this.lens.indexOf(f))return e=this.readUInt8(f),this.l=f+1,e=I.call(this,e?"dbcs":
"sbcs",b-d),c+e;c+=R(this.readUInt16LE(f));f+=2}break;case "sbcs":a=b;c="";f=this.l;for(d=0;d!=b;++d){if(this.lens&&-1!==this.lens.indexOf(f))return e=this.readUInt8(f),this.l=f+1,e=I.call(this,e?"dbcs":"sbcs",b-d),c+e;c+=R(this.readUInt8(f));f+=1}break;case "cstr":a=0;for(c="";0!==(e=this.readUInt8(this.l+a++));)c+=R(e);break;case "wstr":a=0;for(c="";0!==(e=this.readUInt16LE(this.l+a));)c+=R(e),a+=2;a+=2}this.l+=a;return c}function S(a,b){var c=this.slice(this.l,this.l+a.length/2).hexlify("hex");
if(c!==a)throw(b||"")+"Expected "+a+" saw "+c;this.l+=a.length/2}function J(a,b){a.read_shift=I.bind(a);a.chk=S;a.l=b||0;var c=I.bind(a),e=S.bind(a);return[c,e]}function b(a,b){a.read_shift(b)}function C(a,b){a.read_shift(b);return null}function r(a,b){return 1===a.read_shift(b)}function u(a,b){return a.read_shift(2,"u")}function da(a,b){for(var c=u,e=[],d=a.l+b;a.l<d;)e.push(c(a,d-a.l));if(d!==a.l)throw"Slurp error";return e}function T(a){var b=a.read_shift.bind(a),c=b(1);0===b(1)?(b=a.utf8(a.l,
a.l+c),a.l+=c):(b=a.utf16le(a.l,a.l+2*c),a.l+=2*c);return b}function Pa(a){var b=a.read_shift.bind(a),c=b(2),e=b(1),d=e&4,f=e&8,g,h;f&&(g=b(2));d&&(h=b(4));b=0===c?"":b(e&1?"dbcs":"sbcs",c);f&&(a.l+=4*g);d&&(a.l+=h);return b}function ea(a,b){var c;0===a.read_shift.bind(a)(1)?(c=a.utf8(a.l,a.l+b),a.l+=b):c=a.read_shift("dbcs",b);return c}function H(a){var b=a.read_shift(2);return 0===b?(a.l++,""):ea(a,b)}function y(a,b){return a.read_shift("ieee754")}function N(a,b){var c=a.read_shift(2),e=a.read_shift(2),
d=a.read_shift(2);return{r:c,c:e,ixfe:d}}function Qa(a,b){var c=a.read_shift.bind(a),e=c(2),d=c(2,"i"),c=c(2,"i");return[e,d,c]}function oa(a,b){var c=a.read_shift(2),e=a.slice(a.l,a.l+4),d=e[0]&1,f=e[0]&2;a.l+=4;e[0]&=-4;e=0===f?[0,0,0,0,e[0],e[1],e[2],e[3]].readDoubleLE(0):e.readInt32LE(0)>>2;return[c,d?e/100:e]}function Ra(a,b){var c=a.read_shift(2),e=a.read_shift(2),d=a.read_shift(2),f=a.read_shift(2);return{s:{c:d,r:c},e:{c:f,r:e}}}function pa(a,b){var c=a.read_shift(2),e=a.read_shift(2),d=a.read_shift(1),
f=a.read_shift(1);return{s:{c:d,r:c},e:{c:f,r:e}}}function qa(a,b,c){var e=a.read_shift(2),e={fBuiltIn:e&1,fWantAdvise:e>>>1&1,fWantPict:e>>>2&1,fOle:e>>>3&1,fOleLink:e>>>4&1,cf:e>>>5&1023,fIcon:e>>>15&1};if(14849===c.sbcch){var d;a.l+=4;d=b-2-4;c=a.l+d;T(a,d);d=a.read_shift(2);c-=a.l;if(d!==c)throw"Malformed AddinUdf: padding = "+c+" != "+d;a.l+=d}e.body=a.read_shift(b-2);return e}function ra(a,b){var c={};c.Major=a.read_shift(2);c.Minor=a.read_shift(2);return c}function U(a){return function(b,c){b.l+=
a}}function n(a,b){a.l+=1}function fa(a,b){var c=a.read_shift(2);return[c&16383,c>>14&1,c>>15&1]}function sa(a,b){var c=a.read_shift.bind(a),e=c(2),c=c(2),d=fa(a,2),f=fa(a,2);return{s:{r:e,c:d[0],cRel:d[1],rRel:d[2]},e:{r:c,c:f[0],cRel:f[1],rRel:f[2]}}}function ta(a,b){var c=a.read_shift(2),e=fa(a,2);return{r:c,c:e[0],cRel:e[1],rRel:e[2]}}function ua(a,b){var c=N(a,6),e=Sa(a,8),d=a.read_shift(1);a.read_shift(1);a.read_shift(4);var f;f=b-20;var g,h=a.read_shift(2);if(65535==h)a.read_shift(f-2),f=[[],
void 0];else{var m=V(a,h);f!==h+2&&(g=W(a,f-h-2,m));f=[m,g]}return{cell:c,val:e,formula:f,shared:d>>3&1}}function Sa(a){var b;if(65535!==a.readUInt16LE(a.l+6))return y(a);switch(a[a.l]){case 0:return a.l+=8,"String";case 1:return b=1===a[a.l+2],a.l+=8,b;case 2:return b=X[a[a.l+2]],a.l+=8,b;case 3:return a.l+=8,""}}function W(a,q,c){q=a.l+q;for(var e=[],d=0;d!==c.length;++d)switch(c[d][0]){case "PtgArray":for(var f=c[d],g=a,h=1+g.read_shift(1),m=1+g.read_shift(2),l=0,w=[];l!=m&&(w[l]=[]);++l)for(var G=
0;G!=h;++G){var v=w[l],s=G,p=g,t=[];switch(t[0]=p.read_shift(1)){case 4:t[1]=r(p,1)?"TRUE":"FALSE";p.l+=7;break;case 16:t[1]=X[p.l];p.l+=8;break;case 0:p.l+=8;break;case 1:t[1]=y(p,8);break;case 2:t[1]=H(p);break;default:throw"Bad SerAr: "+t[0];}v[s]=t}f[1]=w;e.push(c[d][1]);break;case "PtgMemArea":f=c[d];g=a;h=g.read_shift(2);m=[];for(l=0;l!=h;++l)m.push(Ra(g,8));f[2]=m;e.push(c[d][2])}q-=a.l;0!==q&&e.push(b(a,q));return e}function V(a,q){for(var c=a.l+q,e,d,f=[];c!=a.l;){q=c-a.l;d=a[a.l];e=ga[d];
if(24===d||25===d)d=a[a.l+1],e=(24===d?Ta:Ua)[d];e&&e.f?f.push([e.n,e.f(a,q)]):f.push(b(a,q))}return f}function Y(a,b,c,e){b=b||{s:{c:0,r:0}};var d=[],f,g,h,m,l,w;if(!a[0]||!a[0][0])return"";a[0].forEach(function(a){switch(a[0]){case "PtgUminus":d.push("-"+d.pop());break;case "PtgUplus":d.push("+"+d.pop());break;case "PtgPercent":d.push(d.pop()+"%");break;case "PtgAdd":f=d.pop();g=d.pop();d.push(g+"+"+f);break;case "PtgSub":f=d.pop();g=d.pop();d.push(g+"-"+f);break;case "PtgMul":f=d.pop();g=d.pop();
d.push(g+"*"+f);break;case "PtgDiv":f=d.pop();g=d.pop();d.push(g+"/"+f);break;case "PtgPower":f=d.pop();g=d.pop();d.push(g+"^"+f);break;case "PtgConcat":f=d.pop();g=d.pop();d.push(g+"&"+f);break;case "PtgLt":f=d.pop();g=d.pop();d.push(g+"<"+f);break;case "PtgLe":f=d.pop();g=d.pop();d.push(g+"<="+f);break;case "PtgEq":f=d.pop();g=d.pop();d.push(g+"="+f);break;case "PtgGe":f=d.pop();g=d.pop();d.push(g+">="+f);break;case "PtgGt":f=d.pop();g=d.pop();d.push(g+">"+f);break;case "PtgNe":f=d.pop();g=d.pop();
d.push(g+"<>"+f);break;case "PtgIsect":f=d.pop();g=d.pop();d.push(g+" "+f);break;case "PtgUnion":f=d.pop();g=d.pop();d.push(g+","+f);break;case "PtgRange":break;case "PtgAttrChoose":break;case "PtgAttrGoto":break;case "PtgAttrIf":break;case "PtgRef":h=O(Z(z(a[1][1])),b);d.push(z(h));break;case "PtgRefN":h=O(Z(z(a[1][1])),c);d.push(z(h));break;case "PtgRef3d":m=a[1][1];h=O(a[1][2],b);d.push(e[1][m+1]+"!"+z(h));break;case "PtgFunc":case "PtgFuncVar":var v=a[1][0];a=a[1][1];v||(v=0);var s=d.slice(-v);
d.length-=v;"User"===a&&(a=s.shift());d.push(a+"("+s.join(",")+")");break;case "PtgBool":d.push(a[1]?"TRUE":"FALSE");break;case "PtgInt":d.push(a[1]);break;case "PtgNum":d.push(String(a[1]));break;case "PtgStr":d.push('"'+a[1]+'"');break;case "PtgErr":d.push(a[1]);break;case "PtgArea":w=Va(a[1][1],b);d.push(P(w));break;case "PtgArea3d":m=a[1][1];w=a[1][2];d.push(e[1][m+1]+"!"+P(w));break;case "PtgAttrSum":d.push("SUM("+d.pop()+")");break;case "PtgAttrSemi":break;case "PtgName":l=a[1][2];a=e[0][l].Name;
a in va&&(a=va[a]);d.push(a);break;case "PtgNameX":v=a[1][1];l=a[1][2];e[v+1]?s=e[v+1][l]:e[v-1]&&(s=e[v-1][l]);s||(s={body:"??NAMEX??"});d.push(s.body);break;case "PtgParen":d.push("("+d.pop()+")");break;case "PtgRefErr":d.push("#REF!");break;case "PtgExp":h={c:a[1][1],r:a[1][0]};e.sharedf[z(h)]?(a=e.sharedf[z(h)],d.push(Y(a,b,{c:c.c,r:c.r},e))):d.push(a[1]);break;case "PtgArray":d.push("{"+a[1].map(function(a){return a.map(function(a){return a[1]}).join(",")}).join(";")+"}");break;case "PtgMemArea":break;
case "PtgAttrSpace":break;case "PtgTbl":break;case "PtgMemErr":break;case "PtgMissArg":d.push("");break;case "PtgAreaErr":break;case "PtgAreaN":break;case "PtgRefErr3d":break;case "PtgMemFunc":break;default:throw"Unrecognized Formula Token: "+a;}});return d[0]}function Wa(a){var b={};a=a.content;var c=28,e;e=a.lpstr(c);c+=4+a.readUInt32LE(c);b.UserType=e;e=a.readUInt32LE(c);c+=4;switch(e){case 0:break;case 4294967295:case 4294967294:c+=4;break;default:if(400<e)throw Error("Unsupported Clipboard: "+
e.toString(16));c+=e}e=a.lpstr(c);c+=0===e.length?0:5+e.length;b.Reserved1=e;if(1907550708!==a.readUInt32LE(c))return b;throw"Unsupported Unicode Extension";}function ha(a){function b(a,c,e,d){c.read_shift.bind(c);var q=[c.slice(c.l,c.l+e)];c.l+=e;for(e=ia[c.readUInt16LE(c.l)];e&&"Continue"===e.n;)e=c.readUInt16LE(c.l+2),q.push(c.slice(c.l+4,c.l+4+e)),c.l+=4+e,e=ia[c.readUInt16LE(c.l)];var w=Oa(q);J(w);var G=0;w.lens=[];q.forEach(function(a){w.lens.push(G);G+=a.length});return a.f(w,w.length,d)}function c(a){function c(a,
b){D=a;B=z(a);l[B]=b}var e={opts:{}},d={},l=[],w=a.read_shift.bind(a),G=[],v={},s={},p=null,t=[],ja="",wa={},D,B,xa={},x={enc:!1,sbcch:0,snames:[],sharedf:xa,rrtabid:[],lastuser:"",codepage:0,winlocked:0,wtf:!1},n=[[]],r=0,u=0,Xa=0;n.SheetNames=x.snames;n.sharedf=x.sharedf;for(var ya="",za=0;a.l<a.length-1;){var $=a.l,k=w(2);if(0===k&&"EOF"===ya)break;var A=a.l===a.length?0:w(2),aa,E=ia[k];if(E&&E.f){ya=E.n;if(2===E.r||12==E.r){var C=w(2),A=A-2;if(!x.enc&&C!==k)throw"rt mismatch";12==E.r&&(a.l+=10,
A-=10)}k="EOF"===E.n?E.f(a,A,x):b(E,a,A,x);switch(E.n){case "Date1904":e.opts.Date1904=k;break;case "WriteProtect":e.opts.WriteProtect=!0;break;case "FilePass":throw x.enc=k,2<=F.verbose&&console.error(k),Error("Password protection unsupported");case "WriteAccess":x.lastuser=k;break;case "FileSharing":break;case "CodePage":x.codepage=k;"undefined"!==typeof ka&&(ka=k);"undefined"!==typeof K&&(K=L[k]);break;case "RRTabId":x.rrtabid=k;break;case "WinProtect":x.winlocked=k;break;case "Template":break;
case "RefreshAll":e.opts.RefreshAll=k;break;case "BookBool":break;case "UsesELFs":break;case "MTRSettings":if(k[0]&&k[1])throw"Unsupported threads: "+k;break;case "CalcCount":e.opts.CalcCount=k;break;case "CalcDelta":e.opts.CalcDelta=k;break;case "CalcIter":e.opts.CalcIter=k;break;case "CalcMode":e.opts.CalcMode=k;break;case "CalcPrecision":e.opts.CalcPrecision=k;break;case "CalcSaveRecalc":e.opts.CalcSaveRecalc=k;break;case "CalcRefMode":x.CalcRefMode=k;break;case "Uncalced":break;case "ForceFullCalculation":e.opts.FullCalc=
k;break;case "WsBool":break;case "Header":break;case "Footer":break;case "HCenter":break;case "VCenter":break;case "Pls":break;case "Setup":break;case "DefColWidth":break;case "GCW":break;case "LHRecord":break;case "ColInfo":break;case "Row":break;case "DBCell":break;case "MulBlank":break;case "EntExU2":break;case "SxView":break;case "Sxvd":break;case "SXVI":break;case "SXVDEx":break;case "SxIvd":break;case "SXDI":break;case "SXLI":break;case "SXEx":break;case "QsiSXTag":break;case "Selection":break;
case "Feat":break;case "FeatHdr":case "FeatHdr11":break;case "Feature11":case "Feature12":case "List12":break;case "Blank":break;case "Country":break;case "RecalcId":break;case "DefaultRowHeight":case "DxGCol":break;case "Fbi":case "Fbi2":case "GelFrame":break;case "Font":break;case "XF":break;case "XFCRC":break;case "XFExt":break;case "Style":break;case "StyleExt":break;case "Palette":break;case "ClrtClient":break;case "Theme":break;case "ExtSST":break;case "BookExt":break;case "RichTextStream":break;
case "BkHim":break;case "ScenarioProtect":break;case "ObjProtect":break;case "CondFmt12":break;case "Table":break;case "TableStyles":break;case "SXStreamID":break;case "SXVS":break;case "DConRef":break;case "SXAddl":break;case "ScenMan":break;case "DCon":break;case "CellWatch":break;case "PrintRowCol":break;case "PrintGrid":break;case "PrintSize":break;case "SupBook":n[++r]=[k];u=0;break;case "ExternName":n[r][++u]=k;break;case "XCT":break;case "CRN":break;case "Index":break;case "Lbl":n[0][++Xa]=
k;break;case "ExternSheet":n[r]=n[r].concat(k);u+=k.length;break;case "Protect":l["!protect"]=k;break;case "Password":0!==k&&2<=F.verbose&&console.error("Password verifier: "+k);break;case "Prot4Rev":case "Prot4RevPass":break;case "BoundSheet8":v[k.pos]=k;x.snames.push(k.name);break;case "EOF":if(--za)break;A={};s.e&&(l["!range"]=s,0<s.e.r&&0<s.e.c&&(s.e.r--,s.e.c--,l["!ref"]=P(s),s.e.r++,s.e.c++));for(aa in l)l.hasOwnProperty(aa)&&(A[aa]=l[aa]);""===ja?wa=A:d[ja]=A;break;case "BOF":if(za++)break;
l={};ja=(v[$]||{name:""}).name;G.push([E.n,$,k,v[$]]);break;case "Number":c({c:k.c,r:k.r},{v:k.val,t:"n"});break;case "BoolErr":c({c:k.c,r:k.r},{v:k.val,t:k.t});break;case "RK":c({c:k.c,r:k.r},{ixfe:k.ixfe,v:k.rknum,t:"n"});break;case "MulRk":for(A=k.c;A<=k.C;++A)c({c:A,r:k.r},{ixfe:k.rkrec[A-k.c][0],v:k.rkrec[A-k.c][1],t:"n"});break;case "Formula":switch(k.val){case "String":p=k;break;case "Array Formula":throw"Array Formula unsupported";default:c(k.cell,{v:k.val,f:Y(k.formula,s,k.cell,n),ixfe:k.cell.ixfe,
t:"n"})}break;case "String":p&&(p.val=k,c(p.cell,{v:JSON.stringify(p.val),f:Y(p.formula,s,p.cell,n),ixfe:p.cell.ixfe,t:"s"}),p=null);break;case "Array":break;case "ShrFmla":l[B].f=Y(k[0],s,D,n);xa[B]=k[0];break;case "LabelSst":c({c:k.c,r:k.r},{v:JSON.stringify(t[k.isst]),ixfe:k.ixfe,t:"s"});break;case "Dimensions":s=k;break;case "SST":t=k;break;case "Format":Ya.load(k[1],k[0]);break;case "Scl":break;case "SheetExt":break;case "SheetExtOptional":break;case "ObNoMacros":break;case "ObProj":break;case "CodeName":break;
case "GUIDTypeLib":break;case "Note":break;case "MergeCells":break;case "WOpt":break;case "HLink":case "HLinkTooltip":break;case "PhoneticInfo":break;case "OleObjectSize":break;case "TxO":break;case "DXF":case "DXFN":case "DXFN12":case "DXFN12List":case "DXFN12NoCB":break;case "Dv":case "DVal":break;case "BRAI":case "Series":case "SeriesText":break;case "DConn":break;case "DbOrParamQry":break;case "DBQueryExt":break;case "IFmtRecord":break;case "CondFmt":case "CF":case "CF12":case "CFEx":break;case "NameCmt":break;
case "Dat":case "Begin":case "End":case "StartBlock":case "EndBlock":case "Frame":case "Area":case "Axis":case "AxisLine":case "Tick":break;case "AxesUsed":case "CrtLayout12":case "CrtLayout12A":case "CrtLink":case "CrtLine":case "CrtMlFrt":break;case "LineFormat":case "AreaFormat":case "Chart":case "Chart3d":case "Chart3DBarShape":case "ChartFormat":case "ChartFrtInfo":break;case "PlotArea":case "PlotGrowth":break;case "SeriesList":case "SerParent":case "SerAuxTrend":break;case "DataFormat":case "SerToCrt":case "FontX":break;
case "CatSerRange":case "AxcExt":case "SerFmt":break;case "ShtProps":break;case "DefaultText":case "Text":case "Label":case "CatLab":break;case "DataLabExtContents":break;case "Legend":case "LegendException":break;case "Pie":case "Scatter":break;case "PieFormat":case "MarkerFormat":break;case "StartObject":case "EndObject":break;case "AlRuns":case "ObjectLink":break;case "SIIndex":break;case "AttachedLabel":break;case "Line":case "Bar":break;case "Surf":break;case "AxisParent":break;case "Pos":break;
case "ValueRange":break;case "SXViewEx9":break;case "SXViewLink":break;case "PivotChartBits":break;case "SBaseRef":break;case "TextPropsStream":break;case "LnExt":break;case "MkrExt":break;case "CrtCoopt":break;case "Qsi":case "Qsif":case "Qsir":case "QsiSXTag":break;case "TxtQry":break;case "FilterMode":break;case "AutoFilter":case "AutoFilterInfo":break;case "DropDownObjIds":break;case "Sort":break;case "SortData":break;case "ShapePropsStream":break;case "MsoDrawing":case "MsoDrawingGroup":case "MsoDrawingSelection":break;
case "Obj":break;case "ImData":break;case "Excel9File":break;case "Units":break;case "InterfaceHdr":case "Mms":case "InterfaceEnd":case "DSF":case "BuiltInFnGroupCount":case "Window1":case "Window2":case "HideObj":case "GridSet":case "Guts":case "UserBView":case "UserSViewBegin":case "UserSViewEnd":case "Pane":case "WebPub":case "AutoWebPub":case "RightMargin":case "LeftMargin":case "TopMargin":case "BottomMargin":case "HeaderFooter":case "HFPicture":case "PLV":case "HorizontalPageBreaks":case "VerticalPageBreaks":case "Backup":case "CompressPictures":case "Compat12":break;
case "Continue":case "ContinueFrt12":break;default:throw"Unrecognized Record "+E.n;}G.push([E.n,$,k])}else G.push(["Unrecognized",Number(k).toString(16),k]),w(A)}a=Object.keys(v).sort(function(a,b){return Number(a)-Number(b)}).map(function(a){return v[a].name});var y=[];a.forEach(function(a){y.push(a)});e.Directory=a;e.SheetNames=a;e.Sheets=d;e.Preamble=wa;e.Strings=t;x.enc&&(e.Encryption=x.enc);return e}ka=1252;"undefined"!==typeof L&&(K=L[1252]);var e=a.find("!CompObj");a.find("!SummaryInformation");
var d=a.find("/Workbook");d||(d=a.find("/Book"));if(d)a=c(d.content);else throw Error("Cannot find Workbook stream");e&&Wa(e);return a}function la(a){var b="";if(a["!ref"])for(var c=ma.decode_range(a["!ref"]),e=c.s.r;e<=c.e.r;++e){for(var d=[],f=c.s.c;f<=c.e.c;++f){var g=a[ma.encode_cell({c:f,r:e})];g?("boolean"===typeof g.v&&(g.v=g.v?"TRUE":"FALSE"),d.push(String(g.v).replace(/\\n/g,"\n").replace(/\\t/g,"\t").replace(/\\\\/g,"\\").replace(/\\\"/g,'""'))):d.push("")}b+=d.join(",")+"\n"}return b}function Aa(a){return Number(a.replace(/\$([0-9]+)$/,
"$1"))-1}function Ba(a){return""+(a+1)}function Ca(a){a=a.replace(/^\$([A-Z])/,"$1");for(var b=0,c=0;c!==a.length;++c)b=26*b+a.charCodeAt(c)-64;return b-1}function Da(a){var b="";for(++a;a;a=Math.floor((a-1)/26))b=String.fromCharCode((a-1)%26+65)+b;return b}function Ea(a){return a.replace(/(\$?[A-Z]*)(\$?[0-9]*)/,"$1,$2").split(",")}function Z(a){a=Ea(a);return{c:Ca(a[0]),r:Aa(a[1])}}function z(a){return Da(a.c)+Ba(a.r)}function Fa(a){a=a.split(":").map(Z);return{s:a[0],e:a[a.length-1]}}function P(a,
b){if("undefined"===typeof b||"number"===typeof b)return P(a.s,a.e);"string"!==typeof a&&(a=z(a));"string"!==typeof b&&(b=z(b));return a==b?a:a+":"+b}function O(a,b){b.s?(a.cRel&&(a.c+=b.s.c),a.rRel&&(a.r+=b.s.r)):(a.c+=b.c,a.r+=b.r);for(a.cRel=a.rRel=0;256<=a.c;)a.c-=256;for(;65536<=a.r;)a.r-=65536;return a}function Va(a,b){a.s=O(a.s,b.s);a.e=O(a.e,b.s);return a}if("undefined"!==typeof module&&"undefined"!==typeof require){if("undefined"===typeof L)var L=require("codepage");var ka=1252,K=L[1252]}"undefined"===
typeof Buffer||Buffer.concat||(Buffer.concat=function(a,b){if(!Array.isArray(a))throw new TypeError("Usage: Buffer.concat(list, [length])");if(0===a.length)return new Buffer(0);if(1===a.length)return a[0];var c,e;if("number"!==typeof b)for(c=b=0;c<a.length;c++)e=a[c],b+=e.length;var d=new Buffer(b),f=0;for(c=0;c<a.length;c++)e=a[c],e.copy(d,f),f+=e.length;return d});var Q=Array,Za=function(){return{encode:function(a,b){for(var c="",e,d,f,g,h,m,l=0;l<a.length;)e=a.charCodeAt(l++),d=a.charCodeAt(l++),
f=a.charCodeAt(l++),g=e>>2,e=(e&3)<<4|d>>4,h=(d&15)<<2|f>>6,m=f&63,isNaN(d)?h=m=64:isNaN(f)&&(m=64),c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m);return c},decode:function(a,b){var c="",e,d,f,g,h;a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");
for(var m=0;m<a.length;)e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),e=e<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|h,c+=String.fromCharCode(e),64!=g&&(c+=String.fromCharCode(d)),64!=
h&&(c+=String.fromCharCode(f));return c}}}();"undefined"!==typeof Buffer&&(Buffer.prototype.hexlify=function(){return this.toString("hex")},Buffer.prototype.utf16le=function(a,b){return this.toString("utf16le",a,b).replace(/\u0000/,"").replace(/[\u0001-\u0006]/,"!")},Buffer.prototype.utf8=function(a,b){return this.toString("utf8",a,b)},Buffer.prototype.lpstr=function(a){var b=this.readUInt32LE(a);return 0<b?this.utf8(a+4,a+4+b-1):""},Buffer.prototype.lpwstr=function(a){var b=2*this.readUInt32LE(a);
return this.utf8(a+4,a+4+b-1)},"undefined"!==typeof L&&(Buffer.prototype.lpstr=function(a){var b=this.readUInt32LE(a);if(0===b)return"";if("undefined"===typeof K)return this.utf8(a+4,a+4+b-1);this.slice(a+4,a+4+b-1);for(var c,e=a+4,d="",f;e!=a+4+b;++e){c=this.readUInt8(e);f=K.dec[c];"undefined"===typeof f&&(c=256*c+this.readUInt8(++e),f=K.dec[c]);if("undefined"===typeof f)throw"Unrecognized character "+c.toString(16);if(0===c)break;d+=f}return d}));Array.prototype.readUInt8=function(a){return this[a]};
Array.prototype.readUInt16LE=function(a){return 256*this[a+1]+this[a]};Array.prototype.readInt16LE=function(a){a=this.readUInt16LE(a);return a&32768?-1*(65535-a+1):a};Array.prototype.readUInt32LE=function(a){return 16777216*this[a+3]+65536*this[a+2]+256*this[a+1]+this[a]};Array.prototype.readInt32LE=function(a){a=this.readUInt32LE(a);return a&2147483648?-1*(4294967295-a+1):a};Array.prototype.readDoubleLE=function(a){a=a||0;var b=void 0,c=void 0,e=void 0;void 0===b&&(b=!0);c||(c=8);e||8!==c||(e=52);
var d;d=8*c-e-1;for(var f=(1<<d)-1,g=f>>1,h=-7,m=b?-1:1,c=b?c-1:0,l=this[a+c],c=c+m,b=l&(1<<-h)-1,l=l>>>-h,h=h+d;0<h;b=256*b+this[a+c],c+=m,h-=8);d=b&(1<<-h)-1;b>>>=-h;for(h+=e;0<h;d=256*d+this[a+c],c+=m,h-=8);b===f?a=d?NaN:Infinity*(l?-1:1):(0===b?b=1-g:(d+=Math.pow(2,e),b-=g),a=(l?-1:1)*d*Math.pow(2,b-e));return a};Array.prototype.hexlify=function(){return this.map(function(a){return(16>a?"0":"")+a.toString(16)}).join("")};Array.prototype.utf16le=function(a,b){for(var c="",e=a;e<b;e+=2)c+=String.fromCharCode(this.readUInt16LE(e));
return c.replace(/\u0000/,"").replace(/[\u0001-\u0006]/,"!")};Array.prototype.utf8=function(a,b){for(var c="",e=a;e<b;e++)c+=String.fromCharCode(this.readUInt8(e));return c};Array.prototype.lpstr=function(a){var b=this.readUInt32LE(a);return 0<b?this.utf8(a+4,a+4+b-1):""};Array.prototype.lpwstr=function(a){var b=2*this.readUInt32LE(a);return this.utf8(a+4,a+4+b-1)};var Ya=function(){function a(a,b){var c=String(a);return c.length>=b?c:Array(b-c.length+1).join(0)+c}function b(a){for(var c in h)void 0===
a[c]&&(a[c]=h[c])}function c(a){return a.reverse().split(/;(?!\\)/).reverse().map(g)}function e(a,c,e){var d=[],f="",g=0,h="",l="t",f={},m;b(e=e||{});for(var n="H";g<a.length;)switch(h=a[g]){case '"':for(f="";'"'!==a[++g];)f+=a["\\"===a[g]?++g:g];d.push({t:"t",v:f});break;case "\\":d.push({t:"t",v:a[++g]});++g;break;case "@":d.push({t:"T",v:c});++g;break;case "m":case "d":case "y":case "h":case "s":case "e":m||(m=v(c,e));for(f=a[g];a[++g]===h;)f+=h;"m"===h&&"h"===l.toLowerCase()&&(h="M");"h"===h&&
(h=n);f={t:h,v:f};d.push(f);l=h;break;case "A":f={t:h,v:"A"};"A/P"===a.substr(g,3)?(n="h",g+=3):"AM/PM"===a.substr(g,5)?(f.v="AM",g+=5,n="h"):f.t="t";d.push(f);l=h;break;case "[":for(;"]"!==a[g++];);break;default:if(-1==="$-+/():!^&'~{}<>= ".indexOf(h))throw"unrecognized character "+a[g]+" in "+a;d.push({t:"t",v:h});++g}g=d.length-1;for(l="t";0<=g;--g)switch(d[g].t){case "h":case "H":d[g].t=n;l="h";break;case "d":case "y":case "s":case "M":case "e":l=d[g].t;break;case "m":"s"===l&&(d[g].t="M")}for(g=
0;g<d.length;++g)switch(d[g].t){case "t":case "T":break;case "d":case "m":case "y":case "h":case "H":case "M":case "s":case "A":case "e":d[g].v=s(d[g].t,d[g].v,m);d[g].t="t";break;default:throw"unrecognized type "+d[g].t;}return d.map(function(a){return a.v}).join("")}function d(a,b){"string"===typeof a&&(a=c(a));return"number"!==typeof b?a[3]:0<b?a[0]:0>b?a[1]:a[2]}var f={};String.prototype.reverse=function(){return this.split("").reverse().join("")};var g=function(a){return String(a).reverse()},
h={};f.opts=h;h.date1904=0;h.output="";h.mode="";var m={1:"0",2:"0.00",3:"#,##0",4:"#,##0.00",9:"0%",10:"0.00%",11:"0.00E+00",12:"# ?/?",13:"# ??/??",14:"mm/dd/yy",15:"d-mmm-yy",16:"d-mmm",17:"mmm-yy",18:"h:mm AM/PM",19:"h:mm:ss AM/PM",20:"h:mm",21:"h:mm:ss",22:"m/d/yy h:mm",37:"#,##0 ;(#,##0)",38:"#,##0 ;[Red](#,##0)",39:"#,##0.00;(#,##0.00)",40:"#,##0.00;[Red](#,##0.00)",45:"mm:ss",46:"[h]:mm:ss",47:"mmss.0",48:"##0.0E+0",49:"@"},l=[["Sun","Sunday"],["Mon","Monday"],["Tue","Tuesday"],["Wed","Wednesday"],
["Thu","Thursday"],["Fri","Friday"],["Sat","Saturday"]],w=[["J","Jan","January"],["F","Feb","February"],["M","Mar","March"],["A","Apr","April"],["M","May","May"],["J","Jun","June"],["J","Jul","July"],["A","Aug","August"],["S","Sep","September"],["O","Oct","October"],["N","Nov","November"],["D","Dec","December"]],n=function(a){if("boolean"===typeof a)return a?"TRUE":"FALSE"};f._general=n;var v=function(a,c){var e=Math.floor(a),d=Math.round(86400*(a-e)),f=0,g=[],h={D:e,T:d};b(c=c||{});c.date1904&&(e+=
1462);60===e?(g=[1900,2,29],f=3):(60<e&&--e,f=new Date(1900,0,1),f.setDate(f.getDate()+e-1),g=[f.getFullYear(),f.getMonth()+1,f.getDate()],f=f.getDay(),"excel"===c.mode&&60>e&&(f=(f+6)%7));h.y=g[0];h.m=g[1];h.d=g[2];h.S=d%60;d=Math.floor(d/60);h.M=d%60;d=Math.floor(d/60);h.H=d;h.q=f;return h};f.parse_date_code=v;var s=function(b,c,e){switch(b){case "y":switch(c){case "y":case "yy":return a(e.y%100,2);default:return e.y}case "m":switch(c){case "m":return e.m;case "mm":return a(e.m,2);case "mmm":return w[e.m-
1][1];case "mmmm":return w[e.m-1][2];case "mmmmm":return w[e.m-1][0];default:throw"bad month format: "+c;}case "d":switch(c){case "d":return e.d;case "dd":return a(e.d,2);case "ddd":return l[e.q][0];case "dddd":return l[e.q][1];default:throw"bad day format: "+c;}case "h":switch(c){case "h":return 1+(e.H+11)%12;case "hh":return a(1+(e.H+11)%12,2);default:throw"bad hour format: "+c;}case "H":switch(c){case "h":return e.H;case "hh":return a(e.H,2);default:throw"bad hour format: "+c;}case "M":switch(c){case "m":return e.M;
case "mm":return a(e.M,2);default:throw"bad minute format: "+c;}case "s":switch(c){case "s":return e.S;case "ss":return a(e.S,2);default:throw"bad second format: "+c;}case "e":return e.y;case "A":return(12<=e.h?"P":"A")+c.substr(1);default:throw"bad format type "+b+" in "+c;}};f._split=c;f._eval=e;f._choose=d;f._table=m;f.load=function(a,b){m[b]=a};f.format=function(a,c,f){b(f=f||{});if(0===a)return n(c,f);"number"===typeof a&&(a=m[a]);a=d(a,c,f);return e(a,c,f)};return f}(),Ga={2147483648:{n:"Locale",
t:19},2147483651:{n:"Behavior",t:19},1768515945:{}};(function(){for(var a in Ga)Ga.hasOwnProperty(a)})();var ba="undefined"!==typeof module&&"undefined"!==typeof require?require("cfb"):function(){function a(a){function b(a,c){if(a===M){if(0!==c)throw"DIFAT chain shorter than expected";}else if(a!==$a){for(var d=D[a],f=0;f!=g/4-1&&(u=d.readUInt32LE(4*f))!==M;++f)s.push(u);b(d.readUInt32LE(g-4),c-1)}}function d(a){var b=s[Math.floor(4*a/g)];if(4>g-4*a%g)throw"FAT boundary crossed: "+a+" 4 "+g;return D[b].slice(4*
a%g).readUInt32LE(0)}var f=3,g=512,q=0,m=0,l=0,n=0,r=f=0,v=0,s=[],p=a.slice(0,512);J(p);var t=I.bind(p),l=S.bind(p),q=0,u;l(ab,"Header Signature: ");l(bb,"CLSID: ");t(2);f=t(2);switch(f){case 3:g=512;break;case 4:g=4096;break;default:throw"Major Version: Expected 3 or 4 saw "+f;}var z=p.l,p=a.slice(0,g);J(p,z);t=I.bind(p);l=S.bind(p);z=a.slice(0,g);l("feff","Byte Order: ");switch(u=t(2)){case 9:if(3!==f)throw"MajorVersion/SectorShift Mismatch";break;case 12:if(4!==f)throw"MajorVersion/SectorShift Mismatch";
break;default:throw"Sector Shift: Expected 9 or 12 saw "+u;}l("0600","Mini Sector Shift: ");l("000000000000","Mini Sector Shift: ");q=t(4);if(3===f&&0!==q)throw"# Directory Sectors: Expected 0 saw "+q;t(4);n=t(4);t(4);l("00100000","Mini Stream Cutoff Size: ");f=t(4);m=t(4);r=t(4);l=t(4);for(q=0;512!=p.l&&!((u=t(4))>=Ha);)s[q++]=u;for(var q=Math.ceil((a.length-g)/g),D=[],p=1;p!=q;++p)D[p-1]=a.slice(p*g,(p+1)*g);D[q-1]=a.slice(q*g);b(r,l);a=Array(D.length);for(var B=[],t=function(a){return D[a]},p=
0;p!=D.length;++p)if(l=[],r=(p+n)%D.length,!a[r]){for(q=r;q<=Ha;l.push(q),q=d(q))a[q]=!0;B[r]={nodes:l};B[r].data=Q(l.map(t)).toBuffer()}B[n].name="!Directory";0<m&&f!==M&&(B[f].name="!MiniFAT");B[s[0]].name="!FAT";var C={},x=[],y=[],F=[];a={};(function(a){var b,c;a=B[a].data;for(var e=0;e!=a.length;e+=128){b=a.slice(e,e+128);J(b,64);c=I.bind(b);var d=c(2);if(0===d)break;d=b.utf16le(0,d-(x.length?2:0));x.push(d);var f={name:d};f.type=cb[c(1)];f.color=c(1);f.left=c(4);f.left===na&&delete f.left;f.right=
c(4);f.right===na&&delete f.right;f.child=c(4);f.child===na&&delete f.child;f.clsid=c(16);f.state=c(4);var g=c(8);"0000000000000000"!=g&&(f.ctime=g);g=c(8);"0000000000000000"!=g&&(f.mtime=g);f.start=c(4);f.size=c(4);"root"===f.type?(v=f.start,0<m&&v!==M&&(B[v].name="!StreamData")):4096<=f.size?(f.storage="fat",!B[f.start]&&0<n&&(f.start=(f.start+n)%D.length),B[f.start].name=f.name,f.content=B[f.start].data.slice(0,f.size),J(f.content)):(f.storage="minifat",c=64*f.start,v!==M&&f.start!==M&&(f.content=
B[v].data.slice(c,c+f.size),J(f.content)));f.ctime&&(c=b.slice(b.l-24,b.l-16),c=c.readUInt32LE(4)/1E7*Math.pow(2,32)+c.readUInt32LE(0)/1E7,f.ct=new Date(1E3*(c-11644473600)));f.mtime&&(b=b.slice(b.l-16,b.l-8),b=b.readUInt32LE(4)/1E7*Math.pow(2,32)+b.readUInt32LE(0)/1E7,f.mt=new Date(1E3*(b-11644473600)));C[d]=f;y.push(f)}})(n);(function(a,b,c,e){var d,f=Array(e.length),g=Array(e.length);for(d=0;d!=f.length;++d)f[d]=g[d]=d,c[d]=e[d];for(d=g[0];"undefined"!==typeof d;d=g.shift())a[d].child&&(f[a[d].child]=
d),a[d].left&&(f[a[d].left]=f[d],g.push(a[d].left)),a[d].right&&(f[a[d].right]=f[d],g.push(a[d].right));for(d=1;d!==c.length;++d)if("unknown"!==a[d].type){e=f[d];if(0===e)c[d]=c[0]+"/"+c[d];else for(;0!==e;)c[d]=c[e]+"/"+c[d],e=f[e];f[d]=0}c[0]+="/";for(d=1;d!==c.length;++d)"stream"!==a[d].type&&(c[d]+="/");for(d=0;d!==c.length;++d)b[c[d]]=y[d]})(y,a,F,x);var H=x.shift();x.root=H;return{raw:{header:z,sectors:D},FileIndex:y,FullPaths:F,FullPathDir:a,find:function(a){"/"===a[0]&&(a=H+a);var b=(-1!==
a.indexOf("/")?F:x).map(function(a){return a.toUpperCase()}),c=a.toUpperCase(),b=b.indexOf(c);return-1===b?null:-1!==a.indexOf("/")?y[b]:C[x[b]]}}}var b={read:function(b,e){switch((e||{}).type||"base64"){case "file":var d=b,d=require("fs").readFileSync(d);return a(d);case "base64":b=Za.decode(b);case "binary":b=Na(b)}return a(b)}};b.parse=a;return b}(),Ha=4294967290,M=4294967294,$a=4294967295,ab="d0cf11e0a1b11ae1",na=4294967295,bb="00000000000000000000000000000000",cb="unknown storage stream lockbytes property root".split(" ");
"undefined"!==typeof require&&"undefined"!==typeof exports?(Q=Array,Q.prototype.toBuffer=function(){return Buffer.concat(this[0])},require("fs"),exports.main=function(a){a=ba.read(a[0],{type:"file"});console.log(a)},"undefined"!==typeof module&&require.main===module&&exports.main(process.argv.slice(2))):(Q=Array,Q.prototype.toBuffer=function(){for(var a=[],b=0;b!=this[0].length;++b)a=a.concat(this[0][b]);return a});var db=b,Ia=function(a,b){return 0===b?"":H(a)},eb=r,fb=N,gb=y,hb=u,ib=u,jb=y,kb=r,
lb=u,mb=r,nb=r,ob=u,pb=r,qb=r,rb=u,sb=u,tb=u,ub=r,vb=u,wb=y,xb=r,yb=u,zb=r,Ab=r,Bb=u,Cb=r,Db=u,Eb=r,Fb=r,Gb=y,Hb=r,Ib=H,Jb=r,Kb=y,Lb=r,Mb=r,Nb=r,Ob=b,Pb=b,Qb=b,Rb=b,Sb=b,Tb=b,Ub=b,Vb=b,Wb=b,Xb=b,Yb=b,Zb=b,$b=b,ac=b,bc=b,cc=b,dc=b,ec=b,fc=b,gc=b,hc=b,ic=b,jc=b,kc=b,lc=b,mc=b,nc=b,oc=b,pc=b,qc=b,rc=b,sc=b,tc=b,uc=b,vc=b,wc=b,xc=b,yc=b,zc=b,Ac=b,Bc=b,Cc=b,Dc=b,Ec=b,Fc=b,Gc=b,Hc=b,Ic=b,Jc=b,Kc=b,Lc=b,Mc=b,Nc=b,Oc=b,Pc=b,Qc=b,Rc=b,Sc=b,Tc=b,Uc=b,Vc=b,Wc=b,Xc=b,Yc=b,Zc=b,$c=b,ad=b,bd=b,cd=b,dd=b,ed=b,fd=
b,gd=b,hd=b,id=b,jd=b,kd=b,ld=b,md=b,nd=b,od=b,pd=b,qd=b,rd=b,sd=b,td=b,ud=b,vd=b,wd=b,xd=b,yd=b,zd=b,Ad=b,Bd=b,Cd=b,Dd=b,Ed=b,Fd=b,Gd=b,Hd=b,Id=b,Jd=b,Kd=b,Ld=b,Md=b,Nd=b,Od=b,Pd=b,Qd=b,Rd=b,Sd=b,Td=b,Ud=b,Vd=b,Wd=b,Xd=b,Yd=b,Zd=b,$d=b,ae=H,be=b,ce=b,de=b,ee=b,fe=b,ge=b,he=b,ie=b,je=b,ke=b,le=b,me=b,ne=b,oe=b,pe=b,qe=b,re=b,se=b,te=b,ue=b,ve=b,we=b,xe=b,ye=b,ze=b,Ae=b,Be=b,Ce=b,De=b,Ee=b,Fe=b,Ge=b,He=b,Ie=b,Je=b,Ke=b,Le=b,Me=b,Ne=b,Oe=b,Pe=b,Qe=b,Re=b,Se=b,Te=b,Ue=b,Ve=b,We=b,Xe=b,Ye=b,Ze=b,$e=b,
af=b,bf=b,cf=b,df=b,ef=b,ff=b,gf=b,hf=b,jf=b,kf=b,lf=b,mf=b,nf=b,of=b,pf=b,qf=b,rf=b,sf=b,tf=b,uf=b,vf=b,wf=b,xf=b,yf=b,zf=b,Af=b,Bf=b,Cf=b,Df=b,Ef=b,Ff=b,Gf=b,Hf=b,If=b,Jf=b,Kf=b,Lf=b,Mf=b,Nf=b,Of=b,Pf=b,Qf=b,Rf=b,Sf=b,Tf=b,Uf=b,Vf=b,Wf=b,Xf=b,Yf=b,Zf=b,$f=b,ag=b,bg=b,cg=b,dg=b,eg=b,fg=b,gg=b,hg=b,ig=b,jg=b,kg=b,lg=b,mg=b,ng=b,og=b,pg=b,qg=b,rg=b,sg=b,tg=b,ug=b,vg=b,wg=b,xg=b,yg=b,zg=b,Ag=b,Bg=b,Cg=b,Dg=b,Eg=b,Fg=b,Gg=b,Hg=b,Ig=b,Jg=b,Kg=b,Lg=b,Mg=b,Ng=b,Og=b,Pg=b,Qg=b,Rg=b,Sg=b,Tg=b,Ug=b,Vg=b,Wg=
b,Xg=U(4),Yg=U(4),Zg=U(4),$g=U(8),ah=b,bh=b,ga={1:{n:"PtgExp",f:function(a,b){a.l++;var c=a.read_shift(2),e=a.read_shift(2);return[c,e]}},2:{n:"PtgTbl",f:b},3:{n:"PtgAdd",f:n},4:{n:"PtgSub",f:n},5:{n:"PtgMul",f:n},6:{n:"PtgDiv",f:n},7:{n:"PtgPower",f:n},8:{n:"PtgConcat",f:n},9:{n:"PtgLt",f:n},10:{n:"PtgLe",f:n},11:{n:"PtgEq",f:n},12:{n:"PtgGe",f:n},13:{n:"PtgGt",f:n},14:{n:"PtgNe",f:n},15:{n:"PtgIsect",f:n},16:{n:"PtgUnion",f:n},17:{n:"PtgRange",f:n},18:{n:"PtgUplus",f:n},19:{n:"PtgUminus",f:n},20:{n:"PtgPercent",
f:n},21:{n:"PtgParen",f:n},22:{n:"PtgMissArg",f:n},23:{n:"PtgStr",f:function(a,b){a.l++;return T(a)}},28:{n:"PtgErr",f:function(a,b){a.l++;return X[a.read_shift(1)]}},29:{n:"PtgBool",f:function(a,b){a.l++;return 0!==a.read_shift(1)}},30:{n:"PtgInt",f:function(a,b){a.l++;return a.read_shift(2)}},31:{n:"PtgNum",f:function(a,b){a.l++;return y(a,8)}},32:{n:"PtgArray",f:$g},33:{n:"PtgFunc",f:function(a,b){a.l+=1;var c=a.read_shift(2);return[ch[c],Ja[c]]}},34:{n:"PtgFuncVar",f:function(a,b){a.l++;var c=
a.read_shift(1),e=[a[a.l+1]>>7,a.read_shift(2)&32767];return[c,(0===e[0]?Ja:dh)[e[1]]]}},35:{n:"PtgName",f:function(a,b){var c=a.read_shift(1)>>>5&3,e=a.read_shift(4);return[c,0,e]}},36:{n:"PtgRef",f:function(a,b){var c=(a[a.l]&96)>>5;a.l+=1;var e=ta(a,4);return[c,e]}},37:{n:"PtgArea",f:function(a,b){var c=(a[a.l++]&96)>>5,e=sa(a,8);return[c,e]}},38:{n:"PtgMemArea",f:function(a,b){var c=a.read_shift(1)>>>5&3;a.l+=4;var e=a.read_shift(2);return[c,e]}},39:{n:"PtgMemErr",f:b},40:{n:"PtgMemNoMem",f:b},
41:{n:"PtgMemFunc",f:function(a,b){var c=a.read_shift(1)>>>5&3,e=a.read_shift(2);return[c,e]}},42:{n:"PtgRefErr",f:function(a,b){var c=a.read_shift(1)>>>5&3;a.l+=4;return[c]}},43:{n:"PtgAreaErr",f:b},44:{n:"PtgRefN",f:function(a,b){var c=(a[a.l]&96)>>5;a.l+=1;var e=a.read_shift(2),d=a.read_shift(2),f=(d&32768)>>15,g=(d&16384)>>14,d=d&16383;if(0!==f)for(;256<=d;)d-=256;return[c,{r:e,c:d,cRel:f,rRel:g}]}},45:{n:"PtgAreaN",f:b},57:{n:"PtgNameX",f:function(a,b){var c=a.read_shift(1)>>>5&3,e=a.read_shift(2),
d=a.read_shift(4);return[c,e,d]}},58:{n:"PtgRef3d",f:function(a,b){var c=(a[a.l]&96)>>5;a.l+=1;var e=a.read_shift(2),d=ta(a,4);return[c,e,d]}},59:{n:"PtgArea3d",f:function(a,b){var c=(a[a.l++]&96)>>5,e=a.read_shift(2),d=sa(a,8);return[c,e,d]}},60:{n:"PtgRefErr3d",f:b},61:{n:"PtgAreaErr3d",f:b},255:{}},Ka={64:32,96:32,65:33,97:33,66:34,98:34,67:35,99:35,68:36,100:36,69:37,101:37,70:38,102:38,71:39,103:39,72:40,104:40,73:41,105:41,74:42,106:42,75:43,107:43,76:44,108:44,77:45,109:45,89:57,121:57,90:58,
122:58,91:59,123:59,92:60,124:60,93:61,125:61};(function(){for(var a in Ka)ga[a]=ga[Ka[a]]})();var Ta={},Ua={1:{n:"PtgAttrSemi",f:Yg},2:{n:"PtgAttrIf",f:Xg},4:{n:"PtgAttrChoose",f:function(a,b){a.l+=2;for(var c=a.read_shift(2),e=[],d=0;d<=c;++d)e.push(a.read_shift(2));return e}},8:{n:"PtgAttrGoto",f:function(a,b){a.l+=2;return a.read_shift(2)}},16:{n:"PtgAttrSum",f:Zg},32:{n:"PtgAttrBaxcel",f:ah},64:{n:"PtgAttrSpace",f:function(a,b){a.read_shift(2);var c=a.read_shift(1),e=a.read_shift(1);return[c,
e]}},65:{n:"PtgAttrSpaceSemi",f:bh},255:{}},X={0:"#NULL!",7:"#DIV/0!",15:"#VALUE!",23:"#REF!",29:"#NAME?",36:"#NUM!",42:"#N/A",43:"#GETTING_DATA",255:"#WTF?"},dh={0:"BEEP",1:"OPEN",2:"OPEN.LINKS",3:"CLOSE.ALL",4:"SAVE",5:"SAVE.AS",6:"FILE.DELETE",7:"PAGE.SETUP",8:"PRINT",9:"PRINTER.SETUP",10:"QUIT",11:"NEW.WINDOW",12:"ARRANGE.ALL",13:"WINDOW.SIZE",14:"WINDOW.MOVE",15:"FULL",16:"CLOSE",17:"RUN",22:"SET.PRINT.AREA",23:"SET.PRINT.TITLES",24:"SET.PAGE.BREAK",25:"REMOVE.PAGE.BREAK",26:"FONT",27:"DISPLAY",
28:"PROTECT.DOCUMENT",29:"PRECISION",30:"A1.R1C1",31:"CALCULATE.NOW",32:"CALCULATION",34:"DATA.FIND",35:"EXTRACT",36:"DATA.DELETE",37:"SET.DATABASE",38:"SET.CRITERIA",39:"SORT",40:"DATA.SERIES",41:"TABLE",42:"FORMAT.NUMBER",43:"ALIGNMENT",44:"STYLE",45:"BORDER",46:"CELL.PROTECTION",47:"COLUMN.WIDTH",48:"UNDO",49:"CUT",50:"COPY",51:"PASTE",52:"CLEAR",53:"PASTE.SPECIAL",54:"EDIT.DELETE",55:"INSERT",56:"FILL.RIGHT",57:"FILL.DOWN",61:"DEFINE.NAME",62:"CREATE.NAMES",63:"FORMULA.GOTO",64:"FORMULA.FIND",
65:"SELECT.LAST.CELL",66:"SHOW.ACTIVE.CELL",67:"GALLERY.AREA",68:"GALLERY.BAR",69:"GALLERY.COLUMN",70:"GALLERY.LINE",71:"GALLERY.PIE",72:"GALLERY.SCATTER",73:"COMBINATION",74:"PREFERRED",75:"ADD.OVERLAY",76:"GRIDLINES",77:"SET.PREFERRED",78:"AXES",79:"LEGEND",80:"ATTACH.TEXT",81:"ADD.ARROW",82:"SELECT.CHART",83:"SELECT.PLOT.AREA",84:"PATTERNS",85:"MAIN.CHART",86:"OVERLAY",87:"SCALE",88:"FORMAT.LEGEND",89:"FORMAT.TEXT",90:"EDIT.REPEAT",91:"PARSE",92:"JUSTIFY",93:"HIDE",94:"UNHIDE",95:"WORKSPACE",96:"FORMULA",
97:"FORMULA.FILL",98:"FORMULA.ARRAY",99:"DATA.FIND.NEXT",100:"DATA.FIND.PREV",101:"FORMULA.FIND.NEXT",102:"FORMULA.FIND.PREV",103:"ACTIVATE",104:"ACTIVATE.NEXT",105:"ACTIVATE.PREV",106:"UNLOCKED.NEXT",107:"UNLOCKED.PREV",108:"COPY.PICTURE",109:"SELECT",110:"DELETE.NAME",111:"DELETE.FORMAT",112:"VLINE",113:"HLINE",114:"VPAGE",115:"HPAGE",116:"VSCROLL",117:"HSCROLL",118:"ALERT",119:"NEW",120:"CANCEL.COPY",121:"SHOW.CLIPBOARD",122:"MESSAGE",124:"PASTE.LINK",125:"APP.ACTIVATE",126:"DELETE.ARROW",127:"ROW.HEIGHT",
128:"FORMAT.MOVE",129:"FORMAT.SIZE",130:"FORMULA.REPLACE",131:"SEND.KEYS",132:"SELECT.SPECIAL",133:"APPLY.NAMES",134:"REPLACE.FONT",135:"FREEZE.PANES",136:"SHOW.INFO",137:"SPLIT",138:"ON.WINDOW",139:"ON.DATA",140:"DISABLE.INPUT",142:"OUTLINE",143:"LIST.NAMES",144:"FILE.CLOSE",145:"SAVE.WORKBOOK",146:"DATA.FORM",147:"COPY.CHART",148:"ON.TIME",149:"WAIT",150:"FORMAT.FONT",151:"FILL.UP",152:"FILL.LEFT",153:"DELETE.OVERLAY",155:"SHORT.MENUS",159:"SET.UPDATE.STATUS",161:"COLOR.PALETTE",162:"DELETE.STYLE",
163:"WINDOW.RESTORE",164:"WINDOW.MAXIMIZE",166:"CHANGE.LINK",167:"CALCULATE.DOCUMENT",168:"ON.KEY",169:"APP.RESTORE",170:"APP.MOVE",171:"APP.SIZE",172:"APP.MINIMIZE",173:"APP.MAXIMIZE",174:"BRING.TO.FRONT",175:"SEND.TO.BACK",185:"MAIN.CHART.TYPE",186:"OVERLAY.CHART.TYPE",187:"SELECT.END",188:"OPEN.MAIL",189:"SEND.MAIL",190:"STANDARD.FONT",191:"CONSOLIDATE",192:"SORT.SPECIAL",193:"GALLERY.3D.AREA",194:"GALLERY.3D.COLUMN",195:"GALLERY.3D.LINE",196:"GALLERY.3D.PIE",197:"VIEW.3D",198:"GOAL.SEEK",199:"WORKGROUP",
200:"FILL.GROUP",201:"UPDATE.LINK",202:"PROMOTE",203:"DEMOTE",204:"SHOW.DETAIL",206:"UNGROUP",207:"OBJECT.PROPERTIES",208:"SAVE.NEW.OBJECT",209:"SHARE",210:"SHARE.NAME",211:"DUPLICATE",212:"APPLY.STYLE",213:"ASSIGN.TO.OBJECT",214:"OBJECT.PROTECTION",215:"HIDE.OBJECT",216:"SET.EXTRACT",217:"CREATE.PUBLISHER",218:"SUBSCRIBE.TO",219:"ATTRIBUTES",220:"SHOW.TOOLBAR",222:"PRINT.PREVIEW",223:"EDIT.COLOR",224:"SHOW.LEVELS",225:"FORMAT.MAIN",226:"FORMAT.OVERLAY",227:"ON.RECALC",228:"EDIT.SERIES",229:"DEFINE.STYLE",
240:"LINE.PRINT",243:"ENTER.DATA",249:"GALLERY.RADAR",250:"MERGE.STYLES",251:"EDITION.OPTIONS",252:"PASTE.PICTURE",253:"PASTE.PICTURE.LINK",254:"SPELLING",256:"ZOOM",259:"INSERT.OBJECT",260:"WINDOW.MINIMIZE",265:"SOUND.NOTE",266:"SOUND.PLAY",267:"FORMAT.SHAPE",268:"EXTEND.POLYGON",269:"FORMAT.AUTO",272:"GALLERY.3D.BAR",273:"GALLERY.3D.SURFACE",274:"FILL.AUTO",276:"CUSTOMIZE.TOOLBAR",277:"ADD.TOOL",278:"EDIT.OBJECT",279:"ON.DOUBLECLICK",280:"ON.ENTRY",281:"WORKBOOK.ADD",282:"WORKBOOK.MOVE",283:"WORKBOOK.COPY",
284:"WORKBOOK.OPTIONS",285:"SAVE.WORKSPACE",288:"CHART.WIZARD",289:"DELETE.TOOL",290:"MOVE.TOOL",291:"WORKBOOK.SELECT",292:"WORKBOOK.ACTIVATE",293:"ASSIGN.TO.TOOL",295:"COPY.TOOL",296:"RESET.TOOL",297:"CONSTRAIN.NUMERIC",298:"PASTE.TOOL",302:"WORKBOOK.NEW",305:"SCENARIO.CELLS",306:"SCENARIO.DELETE",307:"SCENARIO.ADD",308:"SCENARIO.EDIT",309:"SCENARIO.SHOW",310:"SCENARIO.SHOW.NEXT",311:"SCENARIO.SUMMARY",312:"PIVOT.TABLE.WIZARD",313:"PIVOT.FIELD.PROPERTIES",314:"PIVOT.FIELD",315:"PIVOT.ITEM",316:"PIVOT.ADD.FIELDS",
318:"OPTIONS.CALCULATION",319:"OPTIONS.EDIT",320:"OPTIONS.VIEW",321:"ADDIN.MANAGER",322:"MENU.EDITOR",323:"ATTACH.TOOLBARS",324:"VBAActivate",325:"OPTIONS.CHART",328:"VBA.INSERT.FILE",330:"VBA.PROCEDURE.DEFINITION",336:"ROUTING.SLIP",338:"ROUTE.DOCUMENT",339:"MAIL.LOGON",342:"INSERT.PICTURE",343:"EDIT.TOOL",344:"GALLERY.DOUGHNUT",350:"CHART.TREND",352:"PIVOT.ITEM.PROPERTIES",354:"WORKBOOK.INSERT",355:"OPTIONS.TRANSITION",356:"OPTIONS.GENERAL",370:"FILTER.ADVANCED",373:"MAIL.ADD.MAILER",374:"MAIL.DELETE.MAILER",
375:"MAIL.REPLY",376:"MAIL.REPLY.ALL",377:"MAIL.FORWARD",378:"MAIL.NEXT.LETTER",379:"DATA.LABEL",380:"INSERT.TITLE",381:"FONT.PROPERTIES",382:"MACRO.OPTIONS",383:"WORKBOOK.HIDE",384:"WORKBOOK.UNHIDE",385:"WORKBOOK.DELETE",386:"WORKBOOK.NAME",388:"GALLERY.CUSTOM",390:"ADD.CHART.AUTOFORMAT",391:"DELETE.CHART.AUTOFORMAT",392:"CHART.ADD.DATA",393:"AUTO.OUTLINE",394:"TAB.ORDER",395:"SHOW.DIALOG",396:"SELECT.ALL",397:"UNGROUP.SHEETS",398:"SUBTOTAL.CREATE",399:"SUBTOTAL.REMOVE",400:"RENAME.OBJECT",412:"WORKBOOK.SCROLL",
413:"WORKBOOK.NEXT",414:"WORKBOOK.PREV",415:"WORKBOOK.TAB.SPLIT",416:"FULL.SCREEN",417:"WORKBOOK.PROTECT",420:"SCROLLBAR.PROPERTIES",421:"PIVOT.SHOW.PAGES",422:"TEXT.TO.COLUMNS",423:"FORMAT.CHARTTYPE",424:"LINK.FORMAT",425:"TRACER.DISPLAY",430:"TRACER.NAVIGATE",431:"TRACER.CLEAR",432:"TRACER.ERROR",433:"PIVOT.FIELD.GROUP",434:"PIVOT.FIELD.UNGROUP",435:"CHECKBOX.PROPERTIES",436:"LABEL.PROPERTIES",437:"LISTBOX.PROPERTIES",438:"EDITBOX.PROPERTIES",439:"PIVOT.REFRESH",440:"LINK.COMBO",441:"OPEN.TEXT",
442:"HIDE.DIALOG",443:"SET.DIALOG.FOCUS",444:"ENABLE.OBJECT",445:"PUSHBUTTON.PROPERTIES",446:"SET.DIALOG.DEFAULT",447:"FILTER",448:"FILTER.SHOW.ALL",449:"CLEAR.OUTLINE",450:"FUNCTION.WIZARD",451:"ADD.LIST.ITEM",452:"SET.LIST.ITEM",453:"REMOVE.LIST.ITEM",454:"SELECT.LIST.ITEM",455:"SET.CONTROL.VALUE",456:"SAVE.COPY.AS",458:"OPTIONS.LISTS.ADD",459:"OPTIONS.LISTS.DELETE",460:"SERIES.AXES",461:"SERIES.X",462:"SERIES.Y",463:"ERRORBAR.X",464:"ERRORBAR.Y",465:"FORMAT.CHART",466:"SERIES.ORDER",467:"MAIL.LOGOFF",
468:"CLEAR.ROUTING.SLIP",469:"APP.ACTIVATE.MICROSOFT",470:"MAIL.EDIT.MAILER",471:"ON.SHEET",472:"STANDARD.WIDTH",473:"SCENARIO.MERGE",474:"SUMMARY.INFO",475:"FIND.FILE",476:"ACTIVE.CELL.FONT",477:"ENABLE.TIPWIZARD",478:"VBA.MAKE.ADDIN",480:"INSERTDATATABLE",481:"WORKGROUP.OPTIONS",482:"MAIL.SEND.MAILER",485:"AUTOCORRECT",489:"POST.DOCUMENT",491:"PICKLIST",493:"VIEW.SHOW",494:"VIEW.DEFINE",495:"VIEW.DELETE",509:"SHEET.BACKGROUND",510:"INSERT.MAP.OBJECT",511:"OPTIONS.MENONO",517:"MSOCHECKS",518:"NORMAL",
519:"LAYOUT",520:"RM.PRINT.AREA",521:"CLEAR.PRINT.AREA",522:"ADD.PRINT.AREA",523:"MOVE.BRK",545:"HIDECURR.NOTE",546:"HIDEALL.NOTES",547:"DELETE.NOTE",548:"TRAVERSE.NOTES",549:"ACTIVATE.NOTES",620:"PROTECT.REVISIONS",621:"UNPROTECT.REVISIONS",647:"OPTIONS.ME",653:"WEB.PUBLISH",667:"NEWWEBQUERY",673:"PIVOT.TABLE.CHART",753:"OPTIONS.SAVE",755:"OPTIONS.SPELL",808:"HIDEALL.INKANNOTS"},Ja={0:"COUNT",1:"IF",2:"ISNA",3:"ISERROR",4:"SUM",5:"AVERAGE",6:"MIN",7:"MAX",8:"ROW",9:"COLUMN",10:"NA",11:"NPV",12:"STDEV",
13:"DOLLAR",14:"FIXED",15:"SIN",16:"COS",17:"TAN",18:"ATAN",19:"PI",20:"SQRT",21:"EXP",22:"LN",23:"LOG10",24:"ABS",25:"INT",26:"SIGN",27:"ROUND",28:"LOOKUP",29:"INDEX",30:"REPT",31:"MID",32:"LEN",33:"VALUE",34:"TRUE",35:"FALSE",36:"AND",37:"OR",38:"NOT",39:"MOD",40:"DCOUNT",41:"DSUM",42:"DAVERAGE",43:"DMIN",44:"DMAX",45:"DSTDEV",46:"VAR",47:"DVAR",48:"TEXT",49:"LINEST",50:"TREND",51:"LOGEST",52:"GROWTH",53:"GOTO",54:"HALT",55:"RETURN",56:"PV",57:"FV",58:"NPER",59:"PMT",60:"RATE",61:"MIRR",62:"IRR",
63:"RAND",64:"MATCH",65:"DATE",66:"TIME",67:"DAY",68:"MONTH",69:"YEAR",70:"WEEKDAY",71:"HOUR",72:"MINUTE",73:"SECOND",74:"NOW",75:"AREAS",76:"ROWS",77:"COLUMNS",78:"OFFSET",79:"ABSREF",80:"RELREF",81:"ARGUMENT",82:"SEARCH",83:"TRANSPOSE",84:"ERROR",85:"STEP",86:"TYPE",87:"ECHO",88:"SET.NAME",89:"CALLER",90:"DEREF",91:"WINDOWS",92:"SERIES",93:"DOCUMENTS",94:"ACTIVE.CELL",95:"SELECTION",96:"RESULT",97:"ATAN2",98:"ASIN",99:"ACOS",100:"CHOOSE",101:"HLOOKUP",102:"VLOOKUP",103:"LINKS",104:"INPUT",105:"ISREF",
106:"GET.FORMULA",107:"GET.NAME",108:"SET.VALUE",109:"LOG",110:"EXEC",111:"CHAR",112:"LOWER",113:"UPPER",114:"PROPER",115:"LEFT",116:"RIGHT",117:"EXACT",118:"TRIM",119:"REPLACE",120:"SUBSTITUTE",121:"CODE",122:"NAMES",123:"DIRECTORY",124:"FIND",125:"CELL",126:"ISERR",127:"ISTEXT",128:"ISNUMBER",129:"ISBLANK",130:"T",131:"N",132:"FOPEN",133:"FCLOSE",134:"FSIZE",135:"FREADLN",136:"FREAD",137:"FWRITELN",138:"FWRITE",139:"FPOS",140:"DATEVALUE",141:"TIMEVALUE",142:"SLN",143:"SYD",144:"DDB",145:"GET.DEF",
146:"REFTEXT",147:"TEXTREF",148:"INDIRECT",149:"REGISTER",150:"CALL",151:"ADD.BAR",152:"ADD.MENU",153:"ADD.COMMAND",154:"ENABLE.COMMAND",155:"CHECK.COMMAND",156:"RENAME.COMMAND",157:"SHOW.BAR",158:"DELETE.MENU",159:"DELETE.COMMAND",160:"GET.CHART.ITEM",161:"DIALOG.BOX",162:"CLEAN",163:"MDETERM",164:"MINVERSE",165:"MMULT",166:"FILES",167:"IPMT",168:"PPMT",169:"COUNTA",170:"CANCEL.KEY",171:"FOR",172:"WHILE",173:"BREAK",174:"NEXT",175:"INITIATE",176:"REQUEST",177:"POKE",178:"EXECUTE",179:"TERMINATE",
180:"RESTART",181:"HELP",182:"GET.BAR",183:"PRODUCT",184:"FACT",185:"GET.CELL",186:"GET.WORKSPACE",187:"GET.WINDOW",188:"GET.DOCUMENT",189:"DPRODUCT",190:"ISNONTEXT",191:"GET.NOTE",192:"NOTE",193:"STDEVP",194:"VARP",195:"DSTDEVP",196:"DVARP",197:"TRUNC",198:"ISLOGICAL",199:"DCOUNTA",200:"DELETE.BAR",201:"UNREGISTER",204:"USDOLLAR",205:"FINDB",206:"SEARCHB",207:"REPLACEB",208:"LEFTB",209:"RIGHTB",210:"MIDB",211:"LENB",212:"ROUNDUP",213:"ROUNDDOWN",214:"ASC",215:"DBCS",216:"RANK",219:"ADDRESS",220:"DAYS360",
221:"TODAY",222:"VDB",223:"ELSE",224:"ELSE.IF",225:"END.IF",226:"FOR.CELL",227:"MEDIAN",228:"SUMPRODUCT",229:"SINH",230:"COSH",231:"TANH",232:"ASINH",233:"ACOSH",234:"ATANH",235:"DGET",236:"CREATE.OBJECT",237:"VOLATILE",238:"LAST.ERROR",239:"CUSTOM.UNDO",240:"CUSTOM.REPEAT",241:"FORMULA.CONVERT",242:"GET.LINK.INFO",243:"TEXT.BOX",244:"INFO",245:"GROUP",246:"GET.OBJECT",247:"DB",248:"PAUSE",251:"RESUME",252:"FREQUENCY",253:"ADD.TOOLBAR",254:"DELETE.TOOLBAR",255:"User",256:"RESET.TOOLBAR",257:"EVALUATE",
258:"GET.TOOLBAR",259:"GET.TOOL",260:"SPELLING.CHECK",261:"ERROR.TYPE",262:"APP.TITLE",263:"WINDOW.TITLE",264:"SAVE.TOOLBAR",265:"ENABLE.TOOL",266:"PRESS.TOOL",267:"REGISTER.ID",268:"GET.WORKBOOK",269:"AVEDEV",270:"BETADIST",271:"GAMMALN",272:"BETAINV",273:"BINOMDIST",274:"CHIDIST",275:"CHIINV",276:"COMBIN",277:"CONFIDENCE",278:"CRITBINOM",279:"EVEN",280:"EXPONDIST",281:"FDIST",282:"FINV",283:"FISHER",284:"FISHERINV",285:"FLOOR",286:"GAMMADIST",287:"GAMMAINV",288:"CEILING",289:"HYPGEOMDIST",290:"LOGNORMDIST",
291:"LOGINV",292:"NEGBINOMDIST",293:"NORMDIST",294:"NORMSDIST",295:"NORMINV",296:"NORMSINV",297:"STANDARDIZE",298:"ODD",299:"PERMUT",300:"POISSON",301:"TDIST",302:"WEIBULL",303:"SUMXMY2",304:"SUMX2MY2",305:"SUMX2PY2",306:"CHITEST",307:"CORREL",308:"COVAR",309:"FORECAST",310:"FTEST",311:"INTERCEPT",312:"PEARSON",313:"RSQ",314:"STEYX",315:"SLOPE",316:"TTEST",317:"PROB",318:"DEVSQ",319:"GEOMEAN",320:"HARMEAN",321:"SUMSQ",322:"KURT",323:"SKEW",324:"ZTEST",325:"LARGE",326:"SMALL",327:"QUARTILE",328:"PERCENTILE",
329:"PERCENTRANK",330:"MODE",331:"TRIMMEAN",332:"TINV",334:"MOVIE.COMMAND",335:"GET.MOVIE",336:"CONCATENATE",337:"POWER",338:"PIVOT.ADD.DATA",339:"GET.PIVOT.TABLE",340:"GET.PIVOT.FIELD",341:"GET.PIVOT.ITEM",342:"RADIANS",343:"DEGREES",344:"SUBTOTAL",345:"SUMIF",346:"COUNTIF",347:"COUNTBLANK",348:"SCENARIO.GET",349:"OPTIONS.LISTS.GET",350:"ISPMT",351:"DATEDIF",352:"DATESTRING",353:"NUMBERSTRING",354:"ROMAN",355:"OPEN.DIALOG",356:"SAVE.DIALOG",357:"VIEW.GET",358:"GETPIVOTDATA",359:"HYPERLINK",360:"PHONETIC",
361:"AVERAGEA",362:"MAXA",363:"MINA",364:"STDEVPA",365:"VARPA",366:"STDEVA",367:"VARA",368:"BAHTTEXT",369:"THAIDAYOFWEEK",370:"THAIDIGIT",371:"THAIMONTHOFYEAR",372:"THAINUMSOUND",373:"THAINUMSTRING",374:"THAISTRINGLENGTH",375:"ISTHAIDIGIT",376:"ROUNDBAHTDOWN",377:"ROUNDBAHTUP",378:"THAIYEAR",379:"RTD"},ch={2:1,3:1,15:1,16:1,17:1,18:1,20:1,21:1,22:1,23:1,24:1,25:1,26:1,27:2,30:2,31:3,32:1,33:1,38:1,39:2,40:3,41:3,42:3,43:3,44:3,45:3,47:3,48:2,53:1,61:3,65:3,66:3,67:1,68:1,69:1,71:1,72:1,73:1,75:1,
76:1,77:1,79:2,80:2,83:1,86:1,90:1,97:2,98:1,99:1,105:1,111:1,112:1,113:1,114:1,117:2,118:1,119:4,121:1,126:1,127:1,128:1,129:1,130:1,131:1,133:1,134:1,135:1,136:2,137:2,138:2,140:1,141:1,142:3,143:4,162:1,163:1,164:1,165:2,172:1,175:2,176:2,177:3,178:2,179:1,184:1,189:3,190:1,195:3,196:3,198:1,199:3,201:1,207:4,210:3,211:1,212:2,213:2,214:1,215:1,229:1,230:1,231:1,232:1,233:1,234:1,235:3,244:1,252:2,257:1,261:1,271:1,273:4,274:2,275:2,276:2,277:3,278:3,279:1,280:3,281:3,282:3,283:1,284:1,285:2,286:4,
287:3,288:2,289:4,290:3,291:3,292:3,293:4,294:1,295:3,296:1,297:3,298:1,299:2,300:3,301:3,302:4,303:2,304:2,305:2,306:2,307:2,308:2,309:3,310:2,311:2,312:2,313:2,314:2,315:2,316:4,325:2,326:2,327:2,328:2,331:2,332:2,337:2,342:1,343:1,346:2,347:1,350:4,351:3,352:1,353:2,360:1,368:1,369:1,370:1,371:1,372:1,373:1,374:1,375:1,376:1,377:1,378:1,65535:0},va={"_xlfn.ACOT":"ACOT","_xlfn.ACOTH":"ACOTH","_xlfn.AGGREGATE":"AGGREGATE","_xlfn.ARABIC":"ARABIC","_xlfn.AVERAGEIF":"AVERAGEIF","_xlfn.AVERAGEIFS":"AVERAGEIFS",
"_xlfn.BASE":"BASE","_xlfn.BETA.DIST":"BETA.DIST","_xlfn.BETA.INV":"BETA.INV","_xlfn.BINOM.DIST":"BINOM.DIST","_xlfn.BINOM.DIST.RANGE":"BINOM.DIST.RANGE","_xlfn.BINOM.INV":"BINOM.INV","_xlfn.BITAND":"BITAND","_xlfn.BITLSHIFT":"BITLSHIFT","_xlfn.BITOR":"BITOR","_xlfn.BITRSHIFT":"BITRSHIFT","_xlfn.BITXOR":"BITXOR","_xlfn.CEILING.MATH":"CEILING.MATH","_xlfn.CEILING.PRECISE":"CEILING.PRECISE","_xlfn.CHISQ.DIST":"CHISQ.DIST","_xlfn.CHISQ.DIST.RT":"CHISQ.DIST.RT","_xlfn.CHISQ.INV":"CHISQ.INV","_xlfn.CHISQ.INV.RT":"CHISQ.INV.RT",
"_xlfn.CHISQ.TEST":"CHISQ.TEST","_xlfn.COMBINA":"COMBINA","_xlfn.CONFIDENCE.NORM":"CONFIDENCE.NORM","_xlfn.CONFIDENCE.T":"CONFIDENCE.T","_xlfn.COT":"COT","_xlfn.COTH":"COTH","_xlfn.COUNTIFS":"COUNTIFS","_xlfn.COVARIANCE.P":"COVARIANCE.P","_xlfn.COVARIANCE.S":"COVARIANCE.S","_xlfn.CSC":"CSC","_xlfn.CSCH":"CSCH","_xlfn.DAYS":"DAYS","_xlfn.DECIMAL":"DECIMAL","_xlfn.ECMA.CEILING":"ECMA.CEILING","_xlfn.ERF.PRECISE":"ERF.PRECISE","_xlfn.ERFC.PRECISE":"ERFC.PRECISE","_xlfn.EXPON.DIST":"EXPON.DIST","_xlfn.F.DIST":"F.DIST",
"_xlfn.F.DIST.RT":"F.DIST.RT","_xlfn.F.INV":"F.INV","_xlfn.F.INV.RT":"F.INV.RT","_xlfn.F.TEST":"F.TEST","_xlfn.FILTERXML":"FILTERXML","_xlfn.FLOOR.MATH":"FLOOR.MATH","_xlfn.FLOOR.PRECISE":"FLOOR.PRECISE","_xlfn.FORMULATEXT":"FORMULATEXT","_xlfn.GAMMA":"GAMMA","_xlfn.GAMMA.DIST":"GAMMA.DIST","_xlfn.GAMMA.INV":"GAMMA.INV","_xlfn.GAMMALN.PRECISE":"GAMMALN.PRECISE","_xlfn.GAUSS":"GAUSS","_xlfn.HYPGEOM.DIST":"HYPGEOM.DIST","_xlfn.IFNA":"IFNA","_xlfn.IFERROR":"IFERROR","_xlfn.IMCOSH":"IMCOSH","_xlfn.IMCOT":"IMCOT",
"_xlfn.IMCSC":"IMCSC","_xlfn.IMCSCH":"IMCSCH","_xlfn.IMSEC":"IMSEC","_xlfn.IMSECH":"IMSECH","_xlfn.IMSINH":"IMSINH","_xlfn.IMTAN":"IMTAN","_xlfn.ISFORMULA":"ISFORMULA","_xlfn.ISO.CEILING":"ISO.CEILING","_xlfn.ISOWEEKNUM":"ISOWEEKNUM","_xlfn.LOGNORM.DIST":"LOGNORM.DIST","_xlfn.LOGNORM.INV":"LOGNORM.INV","_xlfn.MODE.MULT":"MODE.MULT","_xlfn.MODE.SNGL":"MODE.SNGL","_xlfn.MUNIT":"MUNIT","_xlfn.NEGBINOM.DIST":"NEGBINOM.DIST","_xlfn.NETWORKDAYS.INTL":"NETWORKDAYS.INTL","_xlfn.NIGBINOM":"NIGBINOM","_xlfn.NORM.DIST":"NORM.DIST",
"_xlfn.NORM.INV":"NORM.INV","_xlfn.NORM.S.DIST":"NORM.S.DIST","_xlfn.NORM.S.INV":"NORM.S.INV","_xlfn.NUMBERVALUE":"NUMBERVALUE","_xlfn.PDURATION":"PDURATION","_xlfn.PERCENTILE.EXC":"PERCENTILE.EXC","_xlfn.PERCENTILE.INC":"PERCENTILE.INC","_xlfn.PERCENTRANK.EXC":"PERCENTRANK.EXC","_xlfn.PERCENTRANK.INC":"PERCENTRANK.INC","_xlfn.PERMUTATIONA":"PERMUTATIONA","_xlfn.PHI":"PHI","_xlfn.POISSON.DIST":"POISSON.DIST","_xlfn.QUARTILE.EXC":"QUARTILE.EXC","_xlfn.QUARTILE.INC":"QUARTILE.INC","_xlfn.QUERYSTRING":"QUERYSTRING",
"_xlfn.RANK.AVG":"RANK.AVG","_xlfn.RANK.EQ":"RANK.EQ","_xlfn.RRI":"RRI","_xlfn.SEC":"SEC","_xlfn.SECH":"SECH","_xlfn.SHEET":"SHEET","_xlfn.SHEETS":"SHEETS","_xlfn.SKEW.P":"SKEW.P","_xlfn.STDEV.P":"STDEV.P","_xlfn.STDEV.S":"STDEV.S","_xlfn.SUMIFS":"SUMIFS","_xlfn.T.DIST":"T.DIST","_xlfn.T.DIST.2T":"T.DIST.2T","_xlfn.T.DIST.RT":"T.DIST.RT","_xlfn.T.INV":"T.INV","_xlfn.T.INV.2T":"T.INV.2T","_xlfn.T.TEST":"T.TEST","_xlfn.UNICHAR":"UNICHAR","_xlfn.UNICODE":"UNICODE","_xlfn.VAR.P":"VAR.P","_xlfn.VAR.S":"VAR.S",
"_xlfn.WEBSERVICE":"WEBSERVICE","_xlfn.WEIBULL.DIST":"WEIBULL.DIST","_xlfn.WORKDAY.INTL":"WORKDAY.INTL","_xlfn.XOR":"XOR","_xlfn.Z.TEST":"Z.TEST"},ia={6:{n:"Formula",f:ua},10:{n:"EOF",f:C},12:{n:"CalcCount",f:ib},13:{n:"CalcMode",f:lb},14:{n:"CalcPrecision",f:mb},15:{n:"CalcRefMode",f:C},16:{n:"CalcDelta",f:jb},17:{n:"CalcIter",f:kb},18:{n:"Protect",f:Eb},19:{n:"Password",f:yb},20:{n:"Header",f:Ia},21:{n:"Footer",f:Ia},23:{n:"ExternSheet",f:function(a,b,c){var e=[];b=a.l+b;for(var d=a.read_shift(2);0!==
d--;)e.push(Qa(a,b-a.l));if(b!==a.l)throw"Slurp error";a=[];if(1025===c.sbcch){for(b=0;b!=e.length;++b)a.push(c.snames[e[b][1]]);return a}return e}},24:{n:"Lbl",f:function(a,b,c){var e=a.l+b;a.read_shift(2);b=a.read_shift(1);var d=a.read_shift(1);c=a.read_shift(2);a.l+=2;a.read_shift(2);a.l+=4;d=ea(a,d);e=a.l+(e-a.l);c=V(a,c);var f;e!==a.l&&(f=W(a,e-a.l,c));return{chKey:b,Name:d,rgce:[c,f]}}},25:{n:"WinProtect",f:Nb},26:{n:"VerticalPageBreaks",f:Pb},27:{n:"HorizontalPageBreaks",f:Qb},28:{n:"Note",
f:Rb},29:{n:"Selection",f:Sb},34:{n:"Date1904",f:qb},35:{n:"ExternName",f:qa},38:{n:"LeftMargin",f:wb},39:{n:"RightMargin",f:Gb},40:{n:"TopMargin",f:Kb},41:{n:"BottomMargin",f:gb},42:{n:"PrintRowCol",f:Ab},43:{n:"PrintGrid",f:zb},47:{n:"FilePass",f:function(a,b){var c={Type:a.read_shift(2)};switch(c.Type){case 0:u(a);u(a);break;case 1:var e=b-2,d=c||{};d.Info=a.read_shift(2);a.l-=2;switch(d.Info){case 1:var e={},f=e.EncryptionVersionInfo=ra(a,4);if(1!=f.Major||1!=f.Minor)throw"unrecognized version code "+
f.Major+" : "+f.Minor;e.Salt=a.read_shift(16);e.EncryptedVerifier=a.read_shift(16);e.EncryptedVerifierHash=a.read_shift(16);d.Data=e;break;case 2:case 3:case 4:var f={},g=f.EncryptionVersionInfo=ra(a,4),e=e-4;if(2!=g.Minor)throw"unrecognized minor version code: "+g.Minor;if(4<g.Major||2>g.Major)throw"unrecognized major version code: "+g.Major;f.Flags=a.read_shift(4);var e=e-4,g=a.read_shift(4),e=e-4,h=a.read_shift.bind(a),m={};m.Flags=h(4);var l=h(4);if(0!==l)throw"Unrecognized SizeExtra: "+l;m.AlgID=
h(4);switch(m.AlgID){case 0:case 26625:case 26126:case 26127:case 26128:break;default:throw"Unrecognized encryption algorithm: "+m.AlgID;}a.read_shift(g-12);f.EncryptionHeader=m;a.read_shift(e-g);f.EncryptionVerifier=void 0;d.Data=f;break;default:throw"Unrecognized encryptionInfo: "+d.Type;}break;default:throw"Unrecognized Encryption Type "+c.Type;}return c}},49:{n:"Font",f:function(a,b){a.l+=14;return T(a)}},51:{n:"PrintSize",f:Bb},60:{n:"Continue",f:Tb},61:{n:"Window1",f:function(a,b){var c=a.read_shift.bind(a),
e=c(2),d=c(2),f=c(2),g=c(2),h=c(2),m=c(2),l=c(2),n=c(2),c=c(2);return{Pos:[e,d],Dim:[f,g],Flags:h,CurTab:m,FirstTab:l,Selected:n,TabRatio:c}}},64:{n:"Backup",f:eb},65:{n:"Pane",f:Ub},66:{n:"CodePage",f:ob},77:{n:"Pls",f:Vb},80:{n:"DCon",f:Wb},81:{n:"DConRef",f:Xb},82:{n:"DConName",f:Yb},85:{n:"DefColWidth",f:rb},89:{n:"XCT",f:Zb},90:{n:"CRN",f:$b},91:{n:"FileSharing",f:ac},92:{n:"WriteAccess",f:function(a,b,c){if(c.enc)return a.l+=b,"";c=a.l;var e=H(a);a.read_shift(b+c-a.l);return e}},93:{n:"Obj",
f:bc},94:{n:"Uncalced",f:cc},95:{n:"CalcSaveRecalc",f:nb},96:{n:"Template",f:dc},97:{n:"Intl",f:ec},99:{n:"ObjProtect",f:xb},125:{n:"ColInfo",f:fc},128:{n:"Guts",f:function(a,b){a.l+=4;var c=[a.read_shift(2),a.read_shift(2)];0!==c[0]&&c[0]--;0!==c[1]&&c[1]--;if(7<c[0]||7<c[1])throw"Bad Gutters: "+c;return c}},129:{n:"WsBool",f:gc},130:{n:"GridSet",f:tb},131:{n:"HCenter",f:ub},132:{n:"VCenter",f:Mb},133:{n:"BoundSheet8",f:function(a,b){var c=a.read_shift.bind(a),e=c(4),d=c(1)>>6,c=c(1);switch(c){case 0:c=
"Worksheet";break;case 1:c="Macrosheet";break;case 2:c="Chartsheet";break;case 6:c="VBAModule"}var f=T(a);return{pos:e,hs:d,dt:c,name:f}}},134:{n:"WriteProtect",f:Ob},140:{n:"Country",f:da},141:{n:"HideObj",f:vb},144:{n:"Sort",f:hc},146:{n:"Palette",f:ic},151:{n:"Sync",f:jc},152:{n:"LPr",f:kc},153:{n:"DxGCol",f:lc},154:{n:"FnGroupName",f:mc},155:{n:"FilterMode",f:nc},156:{n:"BuiltInFnGroupCount",f:hb},157:{n:"AutoFilterInfo",f:oc},158:{n:"AutoFilter",f:pc},160:{n:"Scl",f:da},161:{n:"Setup",f:qc},
174:{n:"ScenMan",f:rc},175:{n:"SCENARIO",f:sc},176:{n:"SxView",f:tc},177:{n:"Sxvd",f:uc},178:{n:"SXVI",f:vc},180:{n:"SxIvd",f:wc},181:{n:"SXLI",f:xc},182:{n:"SXPI",f:yc},184:{n:"DocRoute",f:zc},185:{n:"RecipName",f:Ac},189:{n:"MulRk",f:function(a,b){for(var c=a.l+b-2,e=a.read_shift(2),d=a.read_shift(2),f=[];a.l<c;)f.push(oa(a));if(a.l!==c)throw"MulRK read error";c=a.read_shift(2);if(f.length!=c-d+1)throw"MulRK length mismatch";return{r:e,c:d,C:c,rkrec:f}}},190:{n:"MulBlank",f:Bc},193:{n:"Mms",f:C},
197:{n:"SXDI",f:Cc},198:{n:"SXDB",f:Dc},199:{n:"SXFDB",f:Ec},200:{n:"SXDBB",f:Fc},201:{n:"SXNum",f:Gc},202:{n:"SxBool",f:Jb},203:{n:"SxErr",f:Hc},204:{n:"SXInt",f:Ic},205:{n:"SXString",f:Jc},206:{n:"SXDtr",f:Kc},207:{n:"SxNil",f:Lc},208:{n:"SXTbl",f:Mc},209:{n:"SXTBRGIITM",f:Nc},210:{n:"SxTbpg",f:Oc},211:{n:"ObProj",f:Pc},213:{n:"SXStreamID",f:Qc},215:{n:"DBCell",f:Rc},216:{n:"SXRng",f:Sc},217:{n:"SxIsxoper",f:Tc},218:{n:"BookBool",f:Uc},220:{n:"DbOrParamQry",f:Vc},221:{n:"ScenarioProtect",f:Hb},
222:{n:"OleObjectSize",f:Wc},224:{n:"XF",f:db},225:{n:"InterfaceHdr",f:function(a,b){var c;if(1200!==(c=a.read_shift(2)))throw"InterfaceHdr codePage "+c;return 1200}},226:{n:"InterfaceEnd",f:C},227:{n:"SXVS",f:Xc},229:{n:"MergeCells",f:Yc},233:{n:"BkHim",f:Zc},235:{n:"MsoDrawingGroup",f:$c},236:{n:"MsoDrawing",f:ad},237:{n:"MsoDrawingSelection",f:bd},239:{n:"PhoneticInfo",f:cd},240:{n:"SxRule",f:dd},241:{n:"SXEx",f:ed},242:{n:"SxFilt",f:fd},244:{n:"SxDXF",f:gd},245:{n:"SxItm",f:hd},246:{n:"SxName",
f:id},247:{n:"SxSelect",f:jd},248:{n:"SXPair",f:kd},249:{n:"SxFmla",f:ld},251:{n:"SxFormat",f:md},252:{n:"SST",f:function(a,b){for(var c=a.read_shift.bind(a),e=c(4),c=c(4),d=[],f=0;f!=c;++f)d.push(Pa(a));d.Count=e;d.Unique=c;return d}},253:{n:"LabelSst",f:function(a,b){var c=N(a);c.isst=a.read_shift(4);return c}},255:{n:"ExtSST",f:function(a,b){var c=a.read_shift.bind(a),e={};e.dsst=c(2);a.read_shift(b-2);return e}},256:{n:"SXVDEx",f:nd},259:{n:"SXFormula",f:od},290:{n:"SXDBEx",f:pd},311:{n:"RRDInsDel",
f:qd},312:{n:"RRDHead",f:rd},315:{n:"RRDChgCell",f:sd},317:{n:"RRTabId",f:da},318:{n:"RRDRenSheet",f:td},319:{n:"RRSort",f:ud},320:{n:"RRDMove",f:vd},330:{n:"RRFormat",f:wd},331:{n:"RRAutoFmt",f:xd},333:{n:"RRInsertSh",f:yd},334:{n:"RRDMoveBegin",f:zd},335:{n:"RRDMoveEnd",f:Ad},336:{n:"RRDInsDelBegin",f:Bd},337:{n:"RRDInsDelEnd",f:Cd},338:{n:"RRDConflict",f:Dd},339:{n:"RRDDefName",f:Ed},340:{n:"RRDRstEtxp",f:Fd},351:{n:"LRng",f:Gd},352:{n:"UsesELFs",f:Lb},353:{n:"DSF",f:C},401:{n:"CUsr",f:Hd},402:{n:"CbUsr",
f:Id},403:{n:"UsrInfo",f:Jd},404:{n:"UsrExcl",f:Kd},405:{n:"FileLock",f:Ld},406:{n:"RRDInfo",f:Md},407:{n:"BCUsrs",f:Nd},408:{n:"UsrChk",f:Od},425:{n:"UserBView",f:Pd},426:{n:"UserSViewBegin",f:Qd},427:{n:"UserSViewEnd",f:Rd},428:{n:"RRDUserView",f:Sd},429:{n:"Qsi",f:Td},430:{n:"SupBook",f:function(a,b,c){var e=a.l+b;b=a.read_shift(2);var d=a.read_shift(2),f;1<=d&&255>=d&&(f=ea(a,d));a=a.read_shift(e-a.l);c.sbcch=d;return[d,b,f,a]}},431:{n:"Prot4Rev",f:Cb},432:{n:"CondFmt",f:Ud},433:{n:"CF",f:Vd},
434:{n:"DVal",f:Wd},437:{n:"DConBin",f:Xd},438:{n:"TxO",f:Yd},439:{n:"RefreshAll",f:Fb},440:{n:"HLink",f:Zd},441:{n:"Lel",f:$d},442:{n:"CodeName",f:ae},443:{n:"SXFDBType",f:be},444:{n:"Prot4RevPass",f:Db},445:{n:"ObNoMacros",f:ce},446:{n:"Dv",f:de},448:{n:"Excel9File",f:C},449:{n:"RecalcId",f:function(a,b){a.read_shift(2);return a.read_shift(4)},r:2},450:{n:"EntExU2",f:C},512:{n:"Dimensions",f:function(a,b){var c=a.read_shift.bind(a),e=c(4),d=c(4),f=c(2),g=c(2);c(2);return{s:{r:e,c:f},e:{r:d,c:g}}}},
513:{n:"Blank",f:fb},515:{n:"Number",f:function(a,b){var c=N(a,6),e=y(a,8);c.val=e;return c}},516:{n:"Label",f:ee},517:{n:"BoolErr",f:function(a,b){var c=N(a,6),e;e=a.read_shift(1);e=1===a.read_shift(1)?X[e]:1===e;c.val=e;c.t=!0===e||!1===e?"b":"e";return c}},519:{n:"String",f:Ib},520:{n:"Row",f:function(a,b){var c=a.read_shift.bind(a),e=c(2),d=c(2),f=c(2);c(2);c(4);c(1);c(1);c(2);return{r:e,c:d,cnt:f-d}}},523:{n:"Index",f:fe},545:{n:"Array",f:function(a,b,c){c=pa(a,6);a.l+=6;b-=12;var e=a.l+b,d,
f=a.read_shift(2);if(65535==f)a.read_shift(b-2),a=[[],void 0];else{var g=V(a,f);b!==f+2&&(d=W(a,e-f-2,g));a=[g,d]}return[c,a]}},549:{n:"DefaultRowHeight",f:function(a,b){var c=a.read_shift(2),e;e=a.read_shift(2);return[{Unsynced:c&1,DyZero:(c&2)>>1,ExAsc:(c&4)>>2,ExDsc:(c&8)>>3},e]}},566:{n:"Table",f:ge},574:{n:"Window2",f:he},638:{n:"RK",f:function(a,b){var c=a.read_shift(2),e=a.read_shift(2),d=oa(a);return{r:c,c:e,ixfe:d[0],rknum:d[1]}}},659:{n:"Style",f:ie},1048:{n:"BigName",f:je},1054:{n:"Format",
f:function(a,b){var c=a.read_shift(2),e=H(a);return[c,e]}},1084:{n:"ContinueBigName",f:ke},1212:{n:"ShrFmla",f:function(a,b,c){pa(a,6);a.l++;c=a.read_shift(1);b-=8;var e=a.l+b,d,f=a.read_shift(2),g=V(a,f);65535==f?(a.read_shift(b-2),a=[[],void 0]):(b!==f+2&&(d=W(a,e-f-2,g)),a=[g,d]);return[a,c]}},2048:{n:"HLinkTooltip",f:le},2049:{n:"WebPub",f:me},2050:{n:"QsiSXTag",f:ne},2051:{n:"DBQueryExt",f:oe},2052:{n:"ExtString",f:pe},2053:{n:"TxtQry",f:qe},2054:{n:"Qsir",f:re},2055:{n:"Qsif",f:se},2056:{n:"RRDTQSIF",
f:te},2057:{n:"BOF",f:function(a,b){var c={};c.BIFFVer=a.read_shift(2);if(1536!=c.BIFFVer)throw"Unexpected BIFF Ver "+c.BIFFVer;a.read_shift(b-2);return c}},2058:{n:"OleDbConn",f:ue},2059:{n:"WOpt",f:ve},2060:{n:"SXViewEx",f:we},2061:{n:"SXTH",f:xe},2062:{n:"SXPIEx",f:ye},2063:{n:"SXVDTEx",f:ze},2064:{n:"SXViewEx9",f:Ae},2066:{n:"ContinueFrt",f:Be},2067:{n:"RealTimeData",f:Ce},2128:{n:"ChartFrtInfo",f:De},2129:{n:"FrtWrapper",f:Ee},2130:{n:"StartBlock",f:Fe},2131:{n:"EndBlock",f:Ge},2132:{n:"StartObject",
f:He},2133:{n:"EndObject",f:Ie},2134:{n:"CatLab",f:Je},2135:{n:"YMult",f:Ke},2136:{n:"SXViewLink",f:Le},2137:{n:"PivotChartBits",f:Me},2138:{n:"FrtFontList",f:Ne},2146:{n:"SheetExt",f:Oe},2147:{n:"BookExt",f:Pe,r:12},2148:{n:"SXAddl",f:Qe},2149:{n:"CrErr",f:Re},2150:{n:"HFPicture",f:Se},2151:{n:"FeatHdr",f:C},2152:{n:"Feat",f:Te},2154:{n:"DataLabExt",f:Ue},2155:{n:"DataLabExtContents",f:Ve},2156:{n:"CellWatch",f:We},2161:{n:"FeatHdr11",f:Xe},2162:{n:"Feature11",f:Ye},2164:{n:"DropDownObjIds",f:Ze},
2165:{n:"ContinueFrt11",f:$e},2166:{n:"DConn",f:af},2167:{n:"List12",f:bf},2168:{n:"Feature12",f:cf},2169:{n:"CondFmt12",f:df},2170:{n:"CF12",f:ef},2171:{n:"CFEx",f:ff},2172:{n:"XFCRC",f:gf},2173:{n:"XFExt",f:hf},2174:{n:"AutoFilter12",f:jf},2175:{n:"ContinueFrt12",f:kf},2180:{n:"MDTInfo",f:lf},2181:{n:"MDXStr",f:mf},2182:{n:"MDXTuple",f:nf},2183:{n:"MDXSet",f:of},2184:{n:"MDXProp",f:pf},2185:{n:"MDXKPI",f:qf},2186:{n:"MDB",f:rf},2187:{n:"PLV",f:sf},2188:{n:"Compat12",f:pb,r:12},2189:{n:"DXF",f:tf},
2190:{n:"TableStyles",f:uf,r:12},2191:{n:"TableStyle",f:vf},2192:{n:"TableStyleElement",f:wf},2194:{n:"StyleExt",f:xf},2195:{n:"NamePublish",f:yf},2196:{n:"NameCmt",f:zf},2197:{n:"SortData",f:Af},2198:{n:"Theme",f:Bf},2199:{n:"GUIDTypeLib",f:Cf},2200:{n:"FnGrp12",f:Df},2201:{n:"NameFnGrp12",f:Ef},2202:{n:"MTRSettings",f:function(a,b){var c=0!==a.read_shift(4),e=0!==a.read_shift(4),d=a.read_shift(4);return[c,e,d]},r:12},2203:{n:"CompressPictures",f:C},2204:{n:"HeaderFooter",f:Ff},2205:{n:"CrtLayout12",
f:Gf},2206:{n:"CrtMlFrt",f:Hf},2207:{n:"CrtMlFrtContinue",f:If},2211:{n:"ForceFullCalculation",f:function(a,b){var c=a.read_shift.bind(a),e=c(2);c(2);c(8);if(2211!=e)throw"Invalid Future Record "+e;return 0!==a.read_shift(4)}},2212:{n:"ShapePropsStream",f:Jf},2213:{n:"TextPropsStream",f:Kf},2214:{n:"RichTextStream",f:Lf},2215:{n:"CrtLayout12A",f:Mf},4097:{n:"Units",f:Nf},4098:{n:"Chart",f:Of},4099:{n:"Series",f:Pf},4102:{n:"DataFormat",f:Qf},4103:{n:"LineFormat",f:Rf},4105:{n:"MarkerFormat",f:Sf},
4106:{n:"AreaFormat",f:Tf},4107:{n:"PieFormat",f:Uf},4108:{n:"AttachedLabel",f:Vf},4109:{n:"SeriesText",f:Wf},4116:{n:"ChartFormat",f:Xf},4117:{n:"Legend",f:Yf},4118:{n:"SeriesList",f:Zf},4119:{n:"Bar",f:$f},4120:{n:"Line",f:ag},4121:{n:"Pie",f:bg},4122:{n:"Area",f:cg},4123:{n:"Scatter",f:dg},4124:{n:"CrtLine",f:eg},4125:{n:"Axis",f:fg},4126:{n:"Tick",f:gg},4127:{n:"ValueRange",f:hg},4128:{n:"CatSerRange",f:ig},4129:{n:"AxisLine",f:jg},4130:{n:"CrtLink",f:kg},4132:{n:"DefaultText",f:lg},4133:{n:"Text",
f:mg},4134:{n:"FontX",f:sb},4135:{n:"ObjectLink",f:ng},4146:{n:"Frame",f:og},4147:{n:"Begin",f:pg},4148:{n:"End",f:qg},4149:{n:"PlotArea",f:rg},4154:{n:"Chart3d",f:sg},4156:{n:"PicF",f:tg},4157:{n:"DropBar",f:ug},4158:{n:"Radar",f:vg},4159:{n:"Surf",f:wg},4160:{n:"RadarArea",f:xg},4161:{n:"AxisParent",f:yg},4163:{n:"LegendException",f:zg},4164:{n:"ShtProps",f:Ag},4165:{n:"SerToCrt",f:Bg},4166:{n:"AxesUsed",f:Cg},4168:{n:"SBaseRef",f:Dg},4170:{n:"SerParent",f:Eg},4171:{n:"SerAuxTrend",f:Fg},4174:{n:"IFmtRecord",
f:Gg},4175:{n:"Pos",f:Hg},4176:{n:"AlRuns",f:Ig},4177:{n:"BRAI",f:Jg},4187:{n:"SerAuxErrBar",f:Kg},4188:{n:"ClrtClient",f:Lg},4189:{n:"SerFmt",f:Mg},4191:{n:"Chart3DBarShape",f:Ng},4192:{n:"Fbi",f:Og},4193:{n:"BopPop",f:Pg},4194:{n:"AxcExt",f:Qg},4195:{n:"Dat",f:Rg},4196:{n:"PlotGrowth",f:Sg},4197:{n:"SIIndex",f:Tg},4198:{n:"GelFrame",f:Ug},4199:{n:"BopPopCustom",f:Vg},4200:{n:"Fbi2",f:Wg},22:{n:"ExternCount",f:b},126:{n:"RK",f:b},127:{n:"ImData",f:b},135:{n:"Addin",f:b},136:{n:"Edg",f:b},137:{n:"Pub",
f:b},145:{n:"Sub",f:b},148:{n:"LHRecord",f:b},149:{n:"LHNGraph",f:b},150:{n:"Sound",f:b},169:{n:"CoordList",f:b},171:{n:"GCW",f:b},188:{n:"ShrFmla",f:b},194:{n:"AddMenu",f:b},195:{n:"DelMenu",f:b},214:{n:"RString",f:b},223:{n:"UDDesc",f:b},234:{n:"TabIdConf",f:b},354:{n:"XL5Modify",f:b},421:{n:"FileSharing2",f:b},536:{n:"Name",f:b},547:{n:"ExternName",f:qa},561:{n:"Font",f:b},1030:{n:"Formula",f:ua},2157:{n:"FeatInfo",f:b},2163:{n:"FeatInfo11",f:b},2177:{n:"SXAddl12",f:b},2240:{n:"AutoWebPub",f:b},
2241:{n:"ListObj",f:b},2242:{n:"ListField",f:b},2243:{n:"ListDV",f:b},2244:{n:"ListCondFmt",f:b},2245:{n:"ListCF",f:b},2246:{n:"FMQry",f:b},2247:{n:"FMSQry",f:b},2248:{n:"PLV",f:b},2249:{n:"LnExt",f:b},2250:{n:"MkrExt",f:b},2251:{n:"CrtCoopt",f:b},0:{}},ma={encode_col:Da,encode_row:Ba,encode_cell:z,encode_range:P,decode_col:Ca,decode_row:Aa,split_cell:Ea,decode_cell:Z,decode_range:Fa,sheet_to_csv:la,make_csv:la,get_formulae:function(a){var b=[],c;for(c in a)if("!"!==c[0]&&a.hasOwnProperty(c)){var e=
a[c],d="",d=e.f?e.f:e.v;b.push(c+"="+d)}return b},sheet_to_row_object_array:function(a){var b,c,e,d,f,g,h=[];if(a["!ref"]){e=Fa(a["!ref"]);d={};for(g=e.s.c;g<=e.e.c;++g)if(b=a[z({c:g,r:e.s.r})])switch(b.t){case "s":case "str":d[g]=JSON.parse(b.v);break;case "n":d[g]=b.v}for(var m=e.s.r+1;m<=e.e.r;++m){f=!0;c=Object.create({__rowNum__:m});for(g=e.s.c;g<=e.e.c;++g){b=a[z({c:g,r:m})];var l=(b||{}).v;if(void 0!==b)switch(b.t){case "s":case "str":void 0!==l&&(l=JSON.parse(l));case "b":case "n":void 0!==
l&&(c[d[g]]=l,f=!1);break;case "e":break;default:throw"unrecognized type "+b.t;}}f||h.push(c)}}return h}},La=function(a){return ha(ba.read(a,{type:"file"}))};F.parse_xlscfb=ha;F.read=function(a,b){return ha(ba.read(a,b))};F.readFile=La;F.utils=ma;F.CFB=ba;if("undefined"!==typeof module&&require.main===module){var Ma=La(process.argv[2]||"Book1.xls"),ca=process.argv[3]||"";""===ca&&(ca=Ma.Directory[0]);var eh=Ma.Sheets[ca];console.log(ca);console.log(la(eh))}})("undefined"!==typeof exports?exports:
XLS);
